import os

with open('src/components/layout/LanguageContext.tsx', 'r', encoding='utf-8') as f:
    text = f.read()

bg_dict = '''  bg: {
    "nav.allTools": "Всички инструменти",
    "nav.compress": "Компресиране",
    "nav.convert": "Конвертиране",
    "nav.merge": "Обединяване",
    "nav.image": "Изображение",
    "nav.organize": "Организиране",
    "nav.resize": "Преоразмеряване",
    "nav.pricing": "Цени",
    "nav.searchPlaceholder": "Търсене в 100+ инструмента...",
    "nav.allToolsBtn": "Всички инструменти",
    
    "hero.tagline": "Вашите файлове, по ваши правила.",
    "hero.title1": "Превърнете файловете си в",
    "hero.title2": "точно това, от което се нуждаете.",
    "hero.subtitle1": "Конвертирайте, компресирайте, редактирайте и организирайте PDF, изображения, Office документи, аудио и видео.",
    "hero.subtitle2": "Файловете се обработват директно в браузъра без качване на сървър за 100% сигурност.",
    
    "trust.badge1": "Обработка в браузъра",
    "trust.badge2": "Автоматично изтриване от сървъра",
    "trust.badge3": "Без регистрация",
    "trust.badge4": "100% Поверително и сигурно",
    
    "homepage.searchPlaceholder": "Намерете подходящия инструмент за вашата задача...",
    "homepage.privateTitle": "100% Поверително",
    "homepage.privateDesc": "Файловете остават при вас",
    "homepage.localTitle": "Локална обработка",
    "homepage.localDesc": "Директно в браузъра",
    "homepage.fallbackTitle": "Сигурен резервен вариант",
    "homepage.fallbackDesc": "TLS криптирана връзка",
    "homepage.dropAnywhere": "Плъзнете файл тук",
    "homepage.chooseFile": "Избор на файл",
    "homepage.orChoose": "или изберете файл от вашето устройство",
    "homepage.methodShown": "Методът на обработка се показва преди стартиране.",
    "homepage.popularTools": "Популярни инструменти",
    "homepage.browseAll": "Разгледайте всички 100+ инструмента →",
    "homepage.viewAll": "Разгледайте всички 100+ инструмента →",
    "homepage.footerNote": "Безплатни основни инструменти. Без скрити абонаменти.",
    
    "tool.compress.desc": "Намаляване на размера на PDF",
    "tool.merge.title": "Обединяване на PDF",
    "tool.merge.desc": "Комбиниране на PDF файлове",
    "tool.split.title": "Разделяне на PDF",
    "tool.split.desc": "Разделяне на страници от PDF",
    "tool.rotate.title": "Завъртане на PDF",
    "tool.rotate.desc": "Завъртане на страници в PDF",
    "tool.watermark.title": "Воден знак в PDF",
    "tool.watermark.desc": "Добавяне на текст или лого",
    "tool.resize.title": "Преоразмеряване на изображение",
    "tool.resize.desc": "Точни пиксели или KB",
    "tool.convert.title": "Конвертор на изображения",
    "tool.convert.desc": "JPG, PNG, WebP",
    "tool.pdfToWord.title": "PDF в Word",
    "tool.pdfToWord.desc": "Редактируем DOCX файл",
    "tool.allTools.title": "Всички инструменти",
    "tool.allTools.desc": "Пълен набор от инструменти",

    "breadcrumb.home": "Начало",
    "breadcrumb.compress": "Компресиране на PDF",
    "compress.title": "Компресиране на PDF под 2 MB",
    "compress.subtitle": "Намалете размера на вашия PDF файл, като запазите възможно най-високото качество.",
    
    "badge.local": "Обработено на това устройство",
    "workspace.dropHere": "Плъзнете вашия PDF файл тук",
    "workspace.pdfOnly": "Само PDF · 100% локална обработка в браузъра",
    "workspace.stayOnDevice": "Вашият PDF файл не напуска това устройство.",
    "workspace.askBeforeTransfer": "FileKit ще поиска разрешение преди всяко временно прехвърляне.",
    
    "trust.privateTitle": "100% Поверително",
    "trust.privateDesc1": "Вашият файл остава под ваш",
    "trust.privateDesc2": "пълен контрол.",
    "trust.localTitle": "Локална обработка",
    "trust.localDesc1": "Обработка в браузъра",
    "trust.localDesc2": "винаги сигурна.",
    "trust.tempTitle": "Временни файлове",
    "trust.tempDesc1": "Сървърните файлове се изтриват",
    "trust.tempDesc2": "автоматично.",
    "trust.trialTitle": "Без скрити абонаменти",
    "trust.trialDesc1": "Ясни и прозрачни условия",
    "trust.trialDesc2": "без изненади.",
    
    "workspace.troubleText": "Имате проблем? Сигурната обработка на сървър е достъпна само с ваше съгласие.",
    "workspace.targetSize": "Целеви размер",
    "workspace.recommended": "Под 2 MB (Препоръчително)",
    "workspace.qualityNote": "Ще намалим размера на файла, запазвайки максимално качество.",
    "workspace.compressBtn": "Компресиране на PDF",
    "workspace.localReady": "Локалната обработка е готова.",
    "workspace.notLeftDevice": "Вашият файл не е напускал това устройство.",
    "workspace.selectFile": "Избор на PDF файл",
    "workspace.remove": "Премахване",
    
    "paywall.title": "Отключване на изтеглянето",
    "paywall.subtitle": "Файлът е обработен успешно. Изберете опция за изтегляне.",
    "paywall.resultVerified": "Проверен резултат",
    "paywall.fileLabel": "Име на документа",
    "paywall.originalLabel": "Оригинален размер",
    "paywall.outputLabel": "Нов размер",
    "paywall.changeLabel": "Промяна на размера",
    "paywall.pagesLabel": "Страници",
    "paywall.locationLabel": "Място на обработка",
    "paywall.localLocation": "Локално (На устройството)",
    "paywall.serverLocation": "Сървър (Облак)",
    "paywall.tlsGuarantee": "TLS криптиране при пренос",
    "paywall.single.title": "Еднократен Premium експорт",
    "paywall.single.billing": "Не се подновява",
    "paywall.single.tagline": "Един файл. Едно плащане. Без абонамент.",
    "paywall.pass.title": "24-часов достъп",
    "paywall.pass.billing": "Не се подновява",
    "paywall.pass.tagline": "Включва 10 сървърни кредита.",
    "paywall.pass.badge": "Най-добра стойност",
    "paywall.pro.title": "Pro Месечен",
    "paywall.pro.billing": "Подновява се месечно",
    "paywall.pro.tagline": "Отказ по всяко време преди следващото плащане.",
    "paywall.ctaUnlock": "Отключване на изтеглянето",
    "paywall.ctaSelect": "Изберете план за отключване",
    "paywall.pending": "Създаване на сигурно плащане...",
    "paywall.cancel": "Обратно към резултата",
    "paywall.viewDetails": "Преглед на детайли",
    "paywall.localTrust": "Обработено поверително на това устройство",
    "paywall.localTrustSub": "Не се изисква качване на файл",
    "paywall.serverTrust": "Криптирано с TLS при пренос",
    "paywall.serverTrustSub": "Обработено в изолирана среда",
    "paywall.checkoutSecure": "Сигурно плащане с криптирана връзка",
    
    "lang.en": "English",
    "lang.bg": "Български",
    "lang.es": "Español",
    "lang.ar": "العربية",
    "lang.tr": "Türkçe",
    "lang.sv": "Svenska"
  },
'''

if 'bg: {' not in text:
    target = 'const translations: Partial<Record<Language, Record<string, string>>> = {'
    text = text.replace(target, target + '\n' + bg_dict)
    with open('src/components/layout/LanguageContext.tsx', 'w', encoding='utf-8') as f:
        f.write(text)
    print('Successfully added full Bulgarian dictionary into LanguageContext.tsx!')
else:
    print('Bulgarian dictionary already exists in LanguageContext.tsx')
