import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, '..', 'src', 'config', 'seo', 'entityDefinitions.ts');

const LOCALES = [
  "en","es","es-419","de","fr","pt","pt-BR","it","nl","ca",
  "sv","da","fi","no","pl","cs","hu","ro","bg","el",
  "sk","sl","ru","uk","lv","lt","tr","ar","he","hi",
  "id","ms","th","vi","fil","ja","ko","zh-CN","zh-TW"
];

const FAMILIES = ["cad","vector","subtitles","apple","image","audio_video","pdf"];

// Entity definition templates per family per locale: receives (title) => string
const ENTITY_TEMPLATES = {
  cad: {
    en: (t) => `FileKit ${t} is an instant vector conversion engine that renders AutoCAD blueprints into universal formats directly in your browser without requiring Autodesk software.`,
    es: (t) => `FileKit ${t} es un motor de conversión vectorial que procesa planos de AutoCAD a formatos universales directamente en tu navegador sin requerir software de Autodesk.`,
    "es-419": (t) => `FileKit ${t} es un motor de conversión vectorial que procesa planos de AutoCAD a formatos universales directamente en tu navegador sin requerir software costoso.`,
    de: (t) => `FileKit ${t} ist eine Vektorkonvertierungs-Engine, die AutoCAD-Pläne direkt im Browser ohne Autodesk-Software in universelle Formate umwandelt.`,
    fr: (t) => `FileKit ${t} est un moteur de conversion vectorielle qui transforme les plans AutoCAD en formats universels directement dans votre navigateur sans logiciel Autodesk.`,
    pt: (t) => `O FileKit ${t} é um motor de conversão vetorial que processa plantas AutoCAD para formatos universais diretamente no navegador sem software da Autodesk.`,
    "pt-BR": (t) => `O FileKit ${t} é um motor de conversão vetorial que processa plantas AutoCAD para formatos universais diretamente no seu navegador sem softwares caros.`,
    it: (t) => `FileKit ${t} è un motore di conversione vettoriale che elabora i progetti AutoCAD in formati universali direttamente nel browser senza software Autodesk.`,
    nl: (t) => `FileKit ${t} is een vectorkeermotor die AutoCAD-blauwdrukken rechtstreeks in uw browser converteert naar universele formaten zonder Autodesk-software.`,
    ca: (t) => `FileKit ${t} és un motor de conversió vectorial que processa plànols d'AutoCAD a formats universals directament al vostre navegador sense programari d'Autodesk.`,
    sv: (t) => `FileKit ${t} är en vektorkonverteringsmotor som återger AutoCAD-ritningar till universella format direkt i din webbläsare utan Autodesk-programvara.`,
    da: (t) => `FileKit ${t} er en vektorkonverteringsmotor, der gengiver AutoCAD-tegninger til universelle formater direkte i din browser uden Autodesk-software.`,
    fi: (t) => `FileKit ${t} on vektorimuunnosmoottori, joka renderöi AutoCAD-piirustukset yleisiin muotoihin suoraan selaimessasi ilman Autodesk-ohjelmistoa.`,
    no: (t) => `FileKit ${t} er en vektorkonverteringsmotor som gjengir AutoCAD-tegninger til universelle formater direkte i nettleseren uten Autodesk-programvare.`,
    pl: (t) => `FileKit ${t} to silnik konwersji wektorowej, który przetwarza rysunki AutoCAD na uniwersalne formaty bezpośrednio w przeglądarce bez oprogramowania Autodesk.`,
    cs: (t) => `FileKit ${t} je vektorový konverzní modul, který převádí výkresy AutoCAD do univerzálních formátů přímo v prohlížeči bez softwaru Autodesk.`,
    hu: (t) => `A FileKit ${t} egy vektorkonverziós motor, amely az AutoCAD tervrajzokat univerzális formátumokká alakítja közvetlenül a böngészőben Autodesk szoftver nélkül.`,
    ro: (t) => `FileKit ${t} este un motor de conversie vectorială care redă planurile AutoCAD în formate universale direct în browser fără software Autodesk.`,
    bg: (t) => `FileKit ${t} е инструмент за векторно конвертиране, който преобразува чертежи на AutoCAD в универсални формати директно в браузъра без софтуер на Autodesk.`,
    el: (t) => `Το FileKit ${t} είναι μια μηχανή διανυσματικής μετατροπής που αποδίδει σχέδια AutoCAD σε καθολικές μορφές απευθείας στον browser σας χωρίς λογισμικό Autodesk.`,
    sk: (t) => `FileKit ${t} je vektorový konverzný nástroj, ktorý vykresľuje výkresy AutoCAD do univerzálnych formátov priamo v prehliadači bez softvéru Autodesk.`,
    sl: (t) => `FileKit ${t} je orodje za vektorsko pretvorbo, ki načrte AutoCAD pretvori v univerzalne formate neposredno v brskalniku brez programske opreme Autodesk.`,
    ru: (t) => `FileKit ${t} — это инструмент векторной конвертации, преобразующий чертежи AutoCAD в универсальные форматы прямо в браузере без программ Autodesk.`,
    uk: (t) => `FileKit ${t} — це інструмент векторної конвертації, що перетворює креслення AutoCAD в універсальні формати безпосередньо у браузері без програм Autodesk.`,
    lv: (t) => `FileKit ${t} ir vektoru konvertēšanas dzinējs, kas atveido AutoCAD rasējumus universālos formātos tieši jūsu pārlūkprogrammā bez Autodesk programmatūras.`,
    lt: (t) => `FileKit ${t} yra vektorinio konvertavimo variklis, atkuriantis AutoCAD brėžinius universaliais formatais tiesiai jūsų naršyklėje be Autodesk programinės įrangos.`,
    tr: (t) => `FileKit ${t}, Autodesk yazılımı gerektirmeden AutoCAD planlarını doğrudan tarayıcınızda evrensel formatlara dönüştüren anında vektör motorudur.`,
    ar: (t) => `أداة ${t} من FileKit هي محرك تحويل متجهي فوري يعرض مخططات AutoCAD بتنسيقات عالمية مباشرة في متصفحك دون الحاجة إلى برنامج Autodesk.`,
    he: (t) => `FileKit ${t} הוא מנוע המרה וקטורי המעבד שרטוטי AutoCAD לפורמטים אוניברסליים ישירות בדפדפן ללא צורך בתוכנת Autodesk.`,
    hi: (t) => `FileKit ${t} एक त्वरित वेक्टर रूपांतरण इंजन है जो Autodesk सॉफ़्टवेयर के बिना सीधे आपके ब्राउज़र में AutoCAD ब्लूप्रिंट को सार्वभौमिक प्रारूपों में प्रस्तुत करता है।`,
    id: (t) => `FileKit ${t} adalah mesin konversi vektor instan yang merender cetak biru AutoCAD ke format universal langsung di browser Anda tanpa perangkat lunak Autodesk.`,
    ms: (t) => `FileKit ${t} ialah enjin penukaran vektor segera yang merender pelan AutoCAD kepada format universal terus dalam pelayar anda tanpa perisian Autodesk.`,
    th: (t) => `FileKit ${t} คือเอ็นจิ้นการแปลงเวกเตอร์ทันทีที่แสดงผลแบบแปลน AutoCAD เป็นรูปแบบสากลโดยตรงในเบราว์เซอร์ของคุณโดยไม่ต้องใช้ซอฟต์แวร์ Autodesk`,
    vi: (t) => `FileKit ${t} là công cụ chuyển đổi vector tức thì hiển thị bản vẽ AutoCAD sang các định dạng phổ biến trực tiếp trong trình duyệt mà không cần phần mềm Autodesk.`,
    fil: (t) => `Ang FileKit ${t} ay isang instant vector conversion engine na nagko-convert ng AutoCAD blueprints sa universal formats direkta sa iyong browser nang walang Autodesk software.`,
    ja: (t) => `FileKit ${t} は、Autodesk ソフトウェアを必要とせず、AutoCAD 図面をブラウザ上で直接ユニバーサル形式に変換する高速ベクターエンジンです。`,
    ko: (t) => `FileKit ${t}은 Autodesk 소프트웨어 없이도 AutoCAD 도면을 브라우저에서 직접 범용 형식으로 렌더링하는 즉각적인 벡터 변환 엔진입니다.`,
    "zh-CN": (t) => `FileKit ${t} 是一款即时矢量转换引擎，无需 Autodesk 软件即可在浏览器中直接将 AutoCAD 图纸呈现为通用格式。`,
    "zh-TW": (t) => `FileKit ${t} 是一款即時向量轉換引擎，無需 Autodesk 軟體即可在瀏覽器中直接將 AutoCAD 工程圖呈現為通用格式。`
  },
  vector: {
    en: (t) => `FileKit ${t} converts professional Adobe Photoshop (PSD), Illustrator (AI), and PostScript (EPS) graphics into web-ready images and vector PDFs.`,
    es: (t) => `FileKit ${t} convierte gráficos de Adobe Photoshop (PSD), Illustrator (AI) y PostScript (EPS) en imágenes optimizadas para la web y documentos PDF vectoriales.`,
    "es-419": (t) => `FileKit ${t} convierte gráficos de Adobe Photoshop (PSD), Illustrator (AI) y PostScript (EPS) en imágenes listas para web y PDFs vectoriales.`,
    de: (t) => `FileKit ${t} konvertiert professionelle Adobe Photoshop (PSD)-, Illustrator (AI)- und PostScript (EPS)-Grafiken in weboptimierte Bilder und Vektor-PDFs.`,
    fr: (t) => `FileKit ${t} convertit les graphiques professionnels Adobe Photoshop (PSD), Illustrator (AI) et PostScript (EPS) en images web et PDF vectoriels.`,
    pt: (t) => `O FileKit ${t} converte gráficos profissionais Adobe Photoshop (PSD), Illustrator (AI) e PostScript (EPS) em imagens para web e PDFs vetoriais.`,
    "pt-BR": (t) => `O FileKit ${t} converte gráficos profissionais Adobe Photoshop (PSD), Illustrator (AI) e PostScript (EPS) em imagens para web e PDFs vetoriais.`,
    it: (t) => `FileKit ${t} converte grafica professionale Adobe Photoshop (PSD), Illustrator (AI) e PostScript (EPS) in immagini pronte per il web e PDF vettoriali.`,
    nl: (t) => `FileKit ${t} converteert professionele Adobe Photoshop (PSD)-, Illustrator (AI)- en PostScript (EPS)-afbeeldingen naar webklare beelden en vector-PDF's.`,
    ca: (t) => `FileKit ${t} converteix gràfics professionals d'Adobe Photoshop (PSD), Illustrator (AI) i PostScript (EPS) en imatges per a web i PDFs vectorials.`,
    sv: (t) => `FileKit ${t} konverterar professionell Adobe Photoshop (PSD)-, Illustrator (AI)- och PostScript (EPS)-grafik till webbklara bilder och vektor-PDF-filer.`,
    da: (t) => `FileKit ${t} konverterer professionel Adobe Photoshop (PSD)-, Illustrator (AI)- og PostScript (EPS)-grafik til webklare billeder og vektor-PDF'er.`,
    fi: (t) => `FileKit ${t} muuntaa ammattimaiset Adobe Photoshop (PSD)-, Illustrator (AI)- ja PostScript (EPS) -grafiikat verkkokäyttöön sopiviksi kuviksi ja vektori-PDF-tiedostoiksi.`,
    no: (t) => `FileKit ${t} konverterer profesjonell Adobe Photoshop (PSD)-, Illustrator (AI)- og PostScript (EPS)-grafikk til nettklare bilder og vektor-PDF-er.`,
    pl: (t) => `FileKit ${t} konwertuje profesjonalną grafikę Adobe Photoshop (PSD), Illustrator (AI) i PostScript (EPS) na obrazy internetowe i wektorowe pliki PDF.`,
    cs: (t) => `FileKit ${t} převádí profesionální grafiku Adobe Photoshop (PSD), Illustrator (AI) a PostScript (EPS) na webové obrázky a vektorové PDF.`,
    hu: (t) => `A FileKit ${t} professzionális Adobe Photoshop (PSD), Illustrator (AI) és PostScript (EPS) grafikákat alakít webkész képekké és vektoros PDF-ekké.`,
    ro: (t) => `FileKit ${t} convertește grafica profesională Adobe Photoshop (PSD), Illustrator (AI) și PostScript (EPS) în imagini optimizate pentru web și PDF-uri vectoriale.`,
    bg: (t) => `FileKit ${t} конвертира професионална графика от Adobe Photoshop (PSD), Illustrator (AI) и PostScript (EPS) в уеб-готови изображения и векторни PDF файлове.`,
    el: (t) => `Το FileKit ${t} μετατρέπει επαγγελματικά γραφικά Adobe Photoshop (PSD), Illustrator (AI) και PostScript (EPS) σε εικόνες ιστού και διανυσματικά PDF.`,
    sk: (t) => `FileKit ${t} prevádza profesionálnu grafiku Adobe Photoshop (PSD), Illustrator (AI) a PostScript (EPS) na webové obrázky a vektorové PDF.`,
    sl: (t) => `FileKit ${t} pretvarja profesionalno grafiko Adobe Photoshop (PSD), Illustrator (AI) in PostScript (EPS) v spletne slike in vektorske PDF-je.`,
    ru: (t) => `FileKit ${t} конвертирует профессиональную графику Adobe Photoshop (PSD), Illustrator (AI) и PostScript (EPS) в веб-изображения и векторные PDF.`,
    uk: (t) => `FileKit ${t} конвертує професійну графіку Adobe Photoshop (PSD), Illustrator (AI) та PostScript (EPS) у веб-зображення та векторні PDF.`,
    lv: (t) => `FileKit ${t} pārveido profesionālu Adobe Photoshop (PSD), Illustrator (AI) un PostScript (EPS) grafiku tīmeklim gatavos attēlos un vektoru PDF.`,
    lt: (t) => `FileKit ${t} konvertuoja profesionalią Adobe Photoshop (PSD), Illustrator (AI) ir PostScript (EPS) grafiką į internetui paruoštus vaizdus ir vektorinius PDF.`,
    tr: (t) => `FileKit ${t}, profesyonel Adobe Photoshop (PSD), Illustrator (AI) ve PostScript (EPS) grafiklerini web için hazır görsellere ve vektör PDF'lere dönüştürür.`,
    ar: (t) => `تقوم أداة ${t} بتحويل ملفات Photoshop (PSD) وIllustrator (AI) وPostScript (EPS) إلى صور جاهزة للويب ومستندات PDF متجهة.`,
    he: (t) => `FileKit ${t} ממיר גרפיקה מקצועית של Adobe Photoshop (PSD), Illustrator (AI) ו-PostScript (EPS) לתמונות מוכנות לרשת וקובצי PDF וקטוריים.`,
    hi: (t) => `FileKit ${t} पेशेवर Adobe Photoshop (PSD), Illustrator (AI), और PostScript (EPS) ग्राफ़िक्स को वेब-रेडी इमेज और वेक्टर PDF में बदलता है।`,
    id: (t) => `FileKit ${t} mengonversi grafik profesional Adobe Photoshop (PSD), Illustrator (AI), dan PostScript (EPS) menjadi gambar siap web dan PDF vektor.`,
    ms: (t) => `FileKit ${t} menukar grafik profesional Adobe Photoshop (PSD), Illustrator (AI) dan PostScript (EPS) kepada imej sedia web dan PDF vektor.`,
    th: (t) => `FileKit ${t} แปลงกราฟิกระดับมืออาชีพ Adobe Photoshop (PSD), Illustrator (AI) และ PostScript (EPS) เป็นรูปภาพพร้อมใช้บนเว็บและ PDF เวกเตอร์`,
    vi: (t) => `FileKit ${t} chuyển đổi đồ họa chuyên nghiệp Adobe Photoshop (PSD), Illustrator (AI) và PostScript (EPS) thành hình ảnh sẵn sàng cho web và PDF vector.`,
    fil: (t) => `Kino-convert ng FileKit ${t} ang propesyonal na Adobe Photoshop (PSD), Illustrator (AI), at PostScript (EPS) graphics sa web-ready images at vector PDFs.`,
    ja: (t) => `FileKit ${t} は、プロフェッショナルな Adobe Photoshop (PSD)、Illustrator (AI)、PostScript (EPS) グラフィックをWeb対応画像およびベクターPDFに変換します。`,
    ko: (t) => `FileKit ${t}은 전문적인 Adobe Photoshop (PSD), Illustrator (AI) 및 PostScript (EPS) 그래픽을 웹용 이미지 및 벡터 PDF로 변환합니다.`,
    "zh-CN": (t) => `FileKit ${t} 可将专业的 Adobe Photoshop (PSD)、Illustrator (AI) 和 PostScript (EPS) 图形转换为网页就绪图像和矢量 PDF。`,
    "zh-TW": (t) => `FileKit ${t} 可將專業的 Adobe Photoshop (PSD)、Illustrator (AI) 和 PostScript (EPS) 圖形轉換為網頁就緒影像和向量 PDF。`
  },
  subtitles: {
    en: (t) => `FileKit ${t} provides 100% in-browser subtitle conversion between SubRip (.srt) and WebVTT (.vtt) with millisecond-accurate timestamp synchronization.`,
    es: (t) => `FileKit ${t} proporciona conversión de subtítulos 100% en el navegador entre SubRip (.srt) y WebVTT (.vtt) con sincronización de marcas de tiempo al milisegundo.`,
    "es-419": (t) => `FileKit ${t} permite convertir subtítulos entre SubRip (.srt) y WebVTT (.vtt) 100% en tu navegador con sincronización exacta al milisegundo.`,
    de: (t) => `FileKit ${t} bietet eine 100% browserbasierte Untertitelkonvertierung zwischen SubRip (.srt) und WebVTT (.vtt) mit millisekundengenauer Synchronisation.`,
    fr: (t) => `FileKit ${t} assure la conversion de sous-titres 100% dans le navigateur entre SubRip (.srt) et WebVTT (.vtt) avec synchronisation précise à la milliseconde.`,
    pt: (t) => `O FileKit ${t} oferece conversão de legendas 100% no navegador entre SubRip (.srt) e WebVTT (.vtt) com sincronização precisa ao milissegundo.`,
    "pt-BR": (t) => `O FileKit ${t} oferece conversão de legendas 100% no navegador entre SubRip (.srt) e WebVTT (.vtt) com sincronização precisa ao milissegundo.`,
    it: (t) => `FileKit ${t} offre la conversione dei sottotitoli al 100% nel browser tra SubRip (.srt) e WebVTT (.vtt) con sincronizzazione accurata al millisecondo.`,
    nl: (t) => `FileKit ${t} biedt 100% browsergebaseerde ondertitelconversie tussen SubRip (.srt) en WebVTT (.vtt) met milliseconde-nauwkeurige synchronisatie.`,
    ca: (t) => `FileKit ${t} proporciona conversió de subtítols 100% al navegador entre SubRip (.srt) i WebVTT (.vtt) amb sincronització precisa al mil·lisegon.`,
    sv: (t) => `FileKit ${t} erbjuder 100% webbläsarbaserad undertextkonvertering mellan SubRip (.srt) och WebVTT (.vtt) med millisekundsexakt synkronisering.`,
    da: (t) => `FileKit ${t} tilbyder 100% browserbaseret undertekstkonvertering mellem SubRip (.srt) og WebVTT (.vtt) med millisekundpræcis synkronisering.`,
    fi: (t) => `FileKit ${t} tarjoaa 100% selaimessa tapahtuvan tekstityksen muuntamisen SubRipin (.srt) ja WebVTT:n (.vtt) välillä millisekunnin tarkkuudella.`,
    no: (t) => `FileKit ${t} gir 100% nettleserbasert undertekstkonvertering mellom SubRip (.srt) og WebVTT (.vtt) med millisekundpresis synkronisering.`,
    pl: (t) => `FileKit ${t} zapewnia 100% konwersję napisów w przeglądarce między SubRip (.srt) a WebVTT (.vtt) z dokładnością do milisekundy.`,
    cs: (t) => `FileKit ${t} poskytuje 100% převod titulků v prohlížeči mezi SubRip (.srt) a WebVTT (.vtt) s přesnou synchronizací na milisekundy.`,
    hu: (t) => `A FileKit ${t} 100%-ban böngészőn belüli feliratkonverziót biztosít a SubRip (.srt) és a WebVTT (.vtt) között ezredmásodperc pontosságú szinkronizálással.`,
    ro: (t) => `FileKit ${t} oferă conversie de subtitrări 100% în browser între SubRip (.srt) și WebVTT (.vtt) cu sincronizare exactă la milisecundă.`,
    bg: (t) => `FileKit ${t} осигурява 100% конвертиране на субтитри в браузъра между SubRip (.srt) и WebVTT (.vtt) с точност до милисекунда.`,
    el: (t) => `Το FileKit ${t} παρέχει 100% μετατροπή υποτίτλων στον browser μεταξύ SubRip (.srt) και WebVTT (.vtt) με συγχρονισμό ακριβείας χιλιοστού δευτερολέπτου.`,
    sk: (t) => `FileKit ${t} poskytuje 100% konverziu titulkov v prehliadači medzi SubRip (.srt) a WebVTT (.vtt) s presnou synchronizáciou na milisekundy.`,
    sl: (t) => `FileKit ${t} omogoča 100% pretvorbo podnapisov v brskalniku med SubRip (.srt) in WebVTT (.vtt) z natančno sinhronizacijo na milisekundo.`,
    ru: (t) => `FileKit ${t} обеспечивает 100% конвертацию субтитров в браузере между SubRip (.srt) и WebVTT (.vtt) с точностью до миллисекунды.`,
    uk: (t) => `FileKit ${t} забезпечує 100% конвертацію субтитрів у браузері між SubRip (.srt) та WebVTT (.vtt) з точністю до мілісекунди.`,
    lv: (t) => `FileKit ${t} nodrošina 100% subtitru konvertēšanu pārlūkprogrammā starp SubRip (.srt) un WebVTT (.vtt) ar milisekundes precizitāti.`,
    lt: (t) => `FileKit ${t} teikia 100% subtitrų konvertavimą naršyklėje tarp SubRip (.srt) ir WebVTT (.vtt) su milisekundžių tikslumo sinchronizavimu.`,
    tr: (t) => `FileKit ${t}, milisaniye hassasiyetinde zaman damgası senkronizasyonu ile SubRip (.srt) ve WebVTT (.vtt) arasında %100 tarayıcı içi altyazı dönüştürme sağlar.`,
    ar: (t) => `توفر أداة ${t} تحويل ترجمات 100% داخل المتصفح بين SubRip (.srt) وWebVTT (.vtt) مع مزامنة زمنية دقيقة بالملي ثانية.`,
    he: (t) => `FileKit ${t} מספק המרת כתוביות 100% בדפדפן בין SubRip (.srt) ל-WebVTT (.vtt) עם סנכרון חותמות זמן בדיוק של מילי-שניות.`,
    hi: (t) => `FileKit ${t} मिलीसेकंड-सटीक टाइमस्टैम्प सिंक्रोनाइज़ेशन के साथ SubRip (.srt) और WebVTT (.vtt) के बीच 100% इन-ब्राउज़र सबटाइटल रूपांतरण प्रदान करता है।`,
    id: (t) => `FileKit ${t} menyediakan konversi subtitle 100% di browser antara SubRip (.srt) dan WebVTT (.vtt) dengan sinkronisasi timestamp yang akurat hingga milidetik.`,
    ms: (t) => `FileKit ${t} menyediakan penukaran sari kata 100% dalam pelayar antara SubRip (.srt) dan WebVTT (.vtt) dengan penyelarasan cap masa tepat milisaat.`,
    th: (t) => `FileKit ${t} ให้บริการแปลงคำบรรยายในเบราว์เซอร์ 100% ระหว่าง SubRip (.srt) และ WebVTT (.vtt) พร้อมการซิงโครไนซ์ประทับเวลาที่แม่นยำระดับมิลลิวินาที`,
    vi: (t) => `FileKit ${t} cung cấp tính năng chuyển đổi phụ đề 100% trong trình duyệt giữa SubRip (.srt) và WebVTT (.vtt) với khả năng đồng bộ hóa dấu thời gian chính xác đến mili giây.`,
    fil: (t) => `Ang FileKit ${t} ay nagbibigay ng 100% in-browser subtitle conversion sa pagitan ng SubRip (.srt) at WebVTT (.vtt) na may millisecond-accurate timestamp sync.`,
    ja: (t) => `FileKit ${t} は、SubRip (.srt) と WebVTT (.vtt) の間でミリ秒精度のタイムスタンプ同期を備えた100%ブラウザ内字幕変換を提供します。`,
    ko: (t) => `FileKit ${t}은 밀리초 단위로 정확한 타임스탬프 동기화를 통해 SubRip(.srt)과 WebVTT(.vtt) 간의 100% 브라우저 내 자막 변환을 제공합니다.`,
    "zh-CN": (t) => `FileKit ${t} 提供 SubRip (.srt) 和 WebVTT (.vtt) 之间的 100% 浏览器内字幕转换，具有毫秒级精确的时间戳同步。`,
    "zh-TW": (t) => `FileKit ${t} 提供 SubRip (.srt) 和 WebVTT (.vtt) 之間的 100% 瀏覽器內字幕轉換，具有毫秒級精確的時間戳記同步。`
  },
  apple: {
    en: (t) => `FileKit ${t} enables Windows, Android, and Linux users to open and convert Apple Pages, Numbers, and Keynote files without Mac hardware or iCloud accounts.`,
    es: (t) => `FileKit ${t} permite a los usuarios de Windows, Android y Linux abrir y convertir archivos de Apple Pages, Numbers y Keynote sin hardware de Mac ni cuentas de iCloud.`,
    "es-419": (t) => `FileKit ${t} permite abrir y convertir archivos Apple Pages, Numbers y Keynote en Windows, Android y Linux sin requerir Mac ni iCloud.`,
    de: (t) => `FileKit ${t} ermöglicht Windows-, Android- und Linux-Benutzern das Öffnen und Konvertieren von Apple Pages-, Numbers- und Keynote-Dateien ohne Mac oder iCloud.`,
    fr: (t) => `FileKit ${t} permet aux utilisateurs Windows, Android et Linux d'ouvrir et de convertir des fichiers Apple Pages, Numbers et Keynote sans Mac ni compte iCloud.`,
    pt: (t) => `O FileKit ${t} permite que utilizadores de Windows, Android e Linux abram e convertam ficheiros Apple Pages, Numbers e Keynote sem Mac ou conta iCloud.`,
    "pt-BR": (t) => `O FileKit ${t} permite que usuários de Windows, Android e Linux abram e convertam arquivos Apple Pages, Numbers e Keynote sem Mac ou conta iCloud.`,
    it: (t) => `FileKit ${t} consente agli utenti Windows, Android e Linux di aprire e convertire file Apple Pages, Numbers e Keynote senza Mac o account iCloud.`,
    nl: (t) => `FileKit ${t} stelt Windows-, Android- en Linux-gebruikers in staat om Apple Pages-, Numbers- en Keynote-bestanden te openen en te converteren zonder Mac of iCloud.`,
    ca: (t) => `FileKit ${t} permet als usuaris de Windows, Android i Linux obrir i convertir fitxers d'Apple Pages, Numbers i Keynote sense Mac ni iCloud.`,
    sv: (t) => `FileKit ${t} gör det möjligt för Windows-, Android- och Linux-användare att öppna och konvertera Apple Pages-, Numbers- och Keynote-filer utan Mac eller iCloud.`,
    da: (t) => `FileKit ${t} gør det muligt for Windows-, Android- og Linux-brugere at åbne og konvertere Apple Pages-, Numbers- og Keynote-filer uden Mac eller iCloud.`,
    fi: (t) => `FileKit ${t} mahdollistaa Apple Pages-, Numbers- ja Keynote-tiedostojen avaamisen ja muuntamisen Windows-, Android- ja Linux-käyttäjille ilman Macia tai iCloudia.`,
    no: (t) => `FileKit ${t} lar Windows-, Android- og Linux-brukere åpne og konvertere Apple Pages-, Numbers- og Keynote-filer uten Mac eller iCloud.`,
    pl: (t) => `FileKit ${t} umożliwia użytkownikom systemów Windows, Android i Linux otwieranie i konwertowanie plików Apple Pages, Numbers i Keynote bez komputera Mac lub iCloud.`,
    cs: (t) => `FileKit ${t} umožňuje uživatelům systémů Windows, Android a Linux otevírat a převádět soubory Apple Pages, Numbers a Keynote bez Macu nebo iCloud.`,
    hu: (t) => `A FileKit ${t} lehetővé teszi a Windows, Android és Linux felhasználók számára az Apple Pages, Numbers és Keynote fájlok megnyitását és konvertálását Mac vagy iCloud nélkül.`,
    ro: (t) => `FileKit ${t} permite utilizatorilor Windows, Android și Linux să deschidă și să convertească fișiere Apple Pages, Numbers și Keynote fără Mac sau iCloud.`,
    bg: (t) => `FileKit ${t} позволява на потребители на Windows, Android и Linux да отварят и конвертират файлове Apple Pages, Numbers и Keynote без Mac или iCloud.`,
    el: (t) => `Το FileKit ${t} επιτρέπει σε χρήστες Windows, Android και Linux να ανοίγουν και να μετατρέπουν αρχεία Apple Pages, Numbers και Keynote χωρίς Mac ή iCloud.`,
    sk: (t) => `FileKit ${t} umožňuje používateľom systémov Windows, Android a Linux otvárať a konvertovať súbory Apple Pages, Numbers a Keynote bez Macu alebo iCloudu.`,
    sl: (t) => `FileKit ${t} uporabnikom sistemov Windows, Android in Linux omogoča odpiranje in pretvorbo datotek Apple Pages, Numbers in Keynote brez Maca ali iClouda.`,
    ru: (t) => `FileKit ${t} позволяет пользователям Windows, Android и Linux открывать и конвертировать файлы Apple Pages, Numbers и Keynote без Mac или iCloud.`,
    uk: (t) => `FileKit ${t} дозволяє користувачам Windows, Android та Linux відкривати та конвертувати файли Apple Pages, Numbers та Keynote без Mac або iCloud.`,
    lv: (t) => `FileKit ${t} ļauj Windows, Android un Linux lietotājiem atvērt un konvertēt Apple Pages, Numbers un Keynote failus bez Mac vai iCloud.`,
    lt: (t) => `FileKit ${t} leidžia Windows, Android ir Linux naudotojams atidaryti ir konvertuoti Apple Pages, Numbers ir Keynote failus be Mac ar iCloud.`,
    tr: (t) => `FileKit ${t}, Windows, Android ve Linux kullanıcılarının Mac donanımı veya iCloud hesabı olmadan Apple Pages, Numbers ve Keynote dosyalarını açmasını ve dönüştürmesini sağlar.`,
    ar: (t) => `تتيح أداة ${t} لمستخدمي Windows وAndroid فتح وتحويل ملفات Apple Pages وNumbers وKeynote بدون أجهزة Mac أو حسابات iCloud.`,
    he: (t) => `FileKit ${t} מאפשר למשתמשי Windows, Android ו-Linux לפתוח ולהמיר קבצי Apple Pages, Numbers ו-Keynote ללא Mac או חשבון iCloud.`,
    hi: (t) => `FileKit ${t} Windows, Android और Linux उपयोगकर्ताओं को Mac हार्डवेयर या iCloud खातों के बिना Apple Pages, Numbers और Keynote फ़ाइलें खोलने और बदलने में सक्षम बनाता है।`,
    id: (t) => `FileKit ${t} memungkinkan pengguna Windows, Android, dan Linux untuk membuka dan mengonversi file Apple Pages, Numbers, dan Keynote tanpa Mac atau akun iCloud.`,
    ms: (t) => `FileKit ${t} membolehkan pengguna Windows, Android dan Linux membuka dan menukar fail Apple Pages, Numbers dan Keynote tanpa Mac atau akaun iCloud.`,
    th: (t) => `FileKit ${t} ช่วยให้ผู้ใช้ Windows, Android และ Linux สามารถเปิดและแปลงไฟล์ Apple Pages, Numbers และ Keynote ได้โดยไม่ต้องใช้ Mac หรือบัญชี iCloud`,
    vi: (t) => `FileKit ${t} cho phép người dùng Windows, Android và Linux mở và chuyển đổi file Apple Pages, Numbers và Keynote mà không cần máy Mac hay tài khoản iCloud.`,
    fil: (t) => `Binibigyang-daan ng FileKit ${t} ang mga gumagamit ng Windows, Android, at Linux na buksan at i-convert ang Apple Pages, Numbers, at Keynote files nang walang Mac o iCloud.`,
    ja: (t) => `FileKit ${t} は、MacハードウェアやiCloudアカウントがなくても、Windows、Android、LinuxユーザーがApple Pages、Numbers、Keynoteファイルを開いて変換できるようにします。`,
    ko: (t) => `FileKit ${t}은 Mac이나 iCloud 계정 없이도 Windows, Android 및 Linux 사용자가 Apple Pages, Numbers 및 Keynote 파일을 열고 변환할 수 있도록 지원합니다.`,
    "zh-CN": (t) => `FileKit ${t} 使 Windows、Android 和 Linux 用户无需 Mac 硬件或 iCloud 账户即可打开和转换 Apple Pages、Numbers 和 Keynote 文件。`,
    "zh-TW": (t) => `FileKit ${t} 使 Windows、Android 和 Linux 使用者無需 Mac 硬體或 iCloud 帳號即可開啟和轉換 Apple Pages、Numbers 和 Keynote 檔案。`
  },
  image: {
    en: (t) => `FileKit ${t} converts high-efficiency photos, WebP, AVIF, HEIC, PNG, and JPG images 100% locally in your browser memory without uploading to third-party servers.`,
    es: (t) => `FileKit ${t} convierte imágenes WebP, AVIF, HEIC, PNG y JPG de forma 100% local en tu navegador sin subir archivos a servidores externos.`,
    "es-419": (t) => `FileKit ${t} convierte imágenes WebP, AVIF, HEIC, PNG y JPG de forma 100% local en tu navegador sin subir archivos a servidores de terceros.`,
    de: (t) => `FileKit ${t} konvertiert WebP-, AVIF-, HEIC-, PNG- und JPG-Bilder zu 100% lokal im Browser ohne Upload zu externen Servern.`,
    fr: (t) => `FileKit ${t} convertit les images WebP, AVIF, HEIC, PNG et JPG 100% localement dans votre navigateur sans téléversement vers des serveurs tiers.`,
    pt: (t) => `O FileKit ${t} converte imagens WebP, AVIF, HEIC, PNG e JPG 100% localmente no seu navegador sem envio para servidores externos.`,
    "pt-BR": (t) => `O FileKit ${t} converte imagens WebP, AVIF, HEIC, PNG e JPG 100% localmente no seu navegador sem envio para servidores externos.`,
    it: (t) => `FileKit ${t} converte immagini WebP, AVIF, HEIC, PNG e JPG al 100% localmente nel browser senza caricare file su server terzi.`,
    nl: (t) => `FileKit ${t} converteert WebP-, AVIF-, HEIC-, PNG- en JPG-afbeeldingen 100% lokaal in uw browser zonder uploaden naar externe servers.`,
    ca: (t) => `FileKit ${t} converteix imatges WebP, AVIF, HEIC, PNG i JPG de manera 100% local al navegador sense pujar fitxers a servidors externs.`,
    sv: (t) => `FileKit ${t} konverterar bilder (WebP, AVIF, HEIC, PNG, JPG) 100% lokalt i din webbläsare utan att ladda upp filer till externa servrar.`,
    da: (t) => `FileKit ${t} konverterer billeder (WebP, AVIF, HEIC, PNG, JPG) 100% lokalt i din browser uden at uploade filer til eksterne servere.`,
    fi: (t) => `FileKit ${t} muuntaa kuvat (WebP, AVIF, HEIC, PNG, JPG) 100% paikallisesti selaimessasi lataamatta tiedostoja ulkoisille palvelimille.`,
    no: (t) => `FileKit ${t} konverterer bilder (WebP, AVIF, HEIC, PNG, JPG) 100% lokalt i nettleseren din uten å laste opp filer til eksterne servere.`,
    pl: (t) => `FileKit ${t} konwertuje obrazy (WebP, AVIF, HEIC, PNG, JPG) w 100% lokalnie w przeglądarce bez przesyłania plików na zewnętrzne serwery.`,
    cs: (t) => `FileKit ${t} převádí obrázky (WebP, AVIF, HEIC, PNG, JPG) 100% lokálně v prohlížeči bez nahrávání souborů na externí servery.`,
    hu: (t) => `A FileKit ${t} a képeket (WebP, AVIF, HEIC, PNG, JPG) 100%-ban helyben, a böngészőben konvertálja külső szerverekre történő feltöltés nélkül.`,
    ro: (t) => `FileKit ${t} convertește imagini (WebP, AVIF, HEIC, PNG, JPG) 100% local în browser fără a încărca fișiere pe servere externe.`,
    bg: (t) => `FileKit ${t} конвертира изображения (WebP, AVIF, HEIC, PNG, JPG) 100% локално в браузъра без качване на файлове на външни сървъри.`,
    el: (t) => `Το FileKit ${t} μετατρέπει εικόνες (WebP, AVIF, HEIC, PNG, JPG) 100% τοπικά στον browser σας χωρίς μεταφόρτωση αρχείων σε εξωτερικούς διακομιστές.`,
    sk: (t) => `FileKit ${t} konvertuje obrázky (WebP, AVIF, HEIC, PNG, JPG) 100% lokálne v prehliadači bez nahrávania súborov na externé servery.`,
    sl: (t) => `FileKit ${t} pretvarja slike (WebP, AVIF, HEIC, PNG, JPG) 100% lokalno v brskalniku brez nalaganja datotek na zunanje strežnike.`,
    ru: (t) => `FileKit ${t} конвертирует изображения (WebP, AVIF, HEIC, PNG, JPG) на 100% локально в браузере без загрузки на внешние серверы.`,
    uk: (t) => `FileKit ${t} конвертує зображення (WebP, AVIF, HEIC, PNG, JPG) на 100% локально у браузері без завантаження на зовнішні сервери.`,
    lv: (t) => `FileKit ${t} konvertē attēlus (WebP, AVIF, HEIC, PNG, JPG) 100% lokāli pārlūkprogrammā bez failu augšupielādes ārējos serveros.`,
    lt: (t) => `FileKit ${t} konvertuoja vaizdus (WebP, AVIF, HEIC, PNG, JPG) 100% lokaliai naršyklėje neįkeldamas failų į išorinius serverius.`,
    tr: (t) => `FileKit ${t}, yüksek verimli fotoğrafları, WebP, AVIF, HEIC, PNG ve JPG görsellerini üçüncü taraf sunuculara yüklemeden %100 yerel olarak tarayıcınızda dönüştürür.`,
    ar: (t) => `تقوم أداة ${t} بتحويل الصور عالية الكفاءة (WebP, AVIF, HEIC, PNG, JPG) محلياً 100% داخل متصفحك دون رفع الملفات إلى أي خادم.`,
    he: (t) => `FileKit ${t} ממיר תמונות WebP, AVIF, HEIC, PNG ו-JPG ב-100% מקומית בזיכרון הדפדפן ללא העלאה לשרתים חיצוניים.`,
    hi: (t) => `FileKit ${t} उच्च-दक्षता वाली फ़ोटो, WebP, AVIF, HEIC, PNG और JPG छवियों को तीसरे पक्ष के सर्वर पर अपलोड किए बिना आपके ब्राउज़र मेमोरी में 100% स्थानीय रूप से बदलता है।`,
    id: (t) => `FileKit ${t} mengonversi foto efisiensi tinggi, gambar WebP, AVIF, HEIC, PNG, dan JPG 100% secara lokal di memori browser tanpa mengunggah ke server pihak ketiga.`,
    ms: (t) => `FileKit ${t} menukar foto kecekapan tinggi, imej WebP, AVIF, HEIC, PNG dan JPG 100% secara setempat dalam memori pelayar tanpa memuat naik ke pelayan pihak ketiga.`,
    th: (t) => `FileKit ${t} แปลงรูปภาพประสิทธิภาพสูง, รูปภาพ WebP, AVIF, HEIC, PNG และ JPG 100% ในหน่วยความจำเบราว์เซอร์ของคุณโดยไม่ต้องอัปโหลดไปยังเซิร์ฟเวอร์ภายนอก`,
    vi: (t) => `FileKit ${t} chuyển đổi ảnh hiệu quả cao, hình ảnh WebP, AVIF, HEIC, PNG và JPG 100% cục bộ trong bộ nhớ trình duyệt mà không cần tải lên máy chủ bên thứ ba.`,
    fil: (t) => `Kino-convert ng FileKit ${t} ang high-efficiency photos, WebP, AVIF, HEIC, PNG, at JPG images nang 100% lokal sa memory ng browser nang hindi nag-a-upload sa third-party servers.`,
    ja: (t) => `FileKit ${t} は、WebP、AVIF、HEIC、PNG、JPG画像を外部サーバーにアップロードすることなく、ブラウザのメモリ内で100%ローカルに変換します。`,
    ko: (t) => `FileKit ${t}은 고효율 사진, WebP, AVIF, HEIC, PNG 및 JPG 이미지를 타사 서버에 업로드하지 않고 브라우저 메모리에서 100% 로컬로 변환합니다.`,
    "zh-CN": (t) => `FileKit ${t} 在浏览器内存中 100% 本地转换高效照片、WebP、AVIF、HEIC、PNG 和 JPG 图像，无需上传到第三方服务器。`,
    "zh-TW": (t) => `FileKit ${t} 在瀏覽器記憶體中 100% 本機轉換高效照片、WebP、AVIF、HEIC、PNG 和 JPG 影像，無需上傳到第三方伺服器。`
  },
  audio_video: {
    en: (t) => `FileKit ${t} is a privacy-first, in-browser media processing engine that converts, edits, and processes audio and video files locally with high performance.`,
    es: (t) => `FileKit ${t} es un motor de procesamiento multimedia centrado en la privacidad para convertir, unir y comprimir archivos multimedia en tu navegador.`,
    "es-419": (t) => `FileKit ${t} es un motor multimedia centrado en la privacidad para convertir, editar y procesar audio y video localmente con alto rendimiento.`,
    de: (t) => `FileKit ${t} ist eine datenschutzorientierte Medien-Engine zur schnellen Konvertierung, Zusammenführung und Komprimierung von Mediendateien direkt im Browser.`,
    fr: (t) => `FileKit ${t} est un moteur de traitement multimédia axé sur la confidentialité pour convertir, fusionner et compresser vos fichiers directement dans votre navigateur.`,
    pt: (t) => `O FileKit ${t} é um motor multimídia focado em privacidade para converter, juntar e comprimir arquivos diretamente no seu navegador.`,
    "pt-BR": (t) => `O FileKit ${t} é um motor multimídia focado em privacidade para converter, juntar e comprimir arquivos diretamente no seu navegador.`,
    it: (t) => `FileKit ${t} è un motore multimediale incentrato sulla privacy per convertire, unire e comprimere file direttamente nel tuo browser.`,
    nl: (t) => `FileKit ${t} is een privacygerichte media-engine die audio- en videobestanden lokaal in de browser converteert, bewerkt en comprimeert.`,
    ca: (t) => `FileKit ${t} és un motor multimèdia centrat en la privadesa per convertir, unir i comprimir fitxers multimèdia directament al vostre navegador.`,
    sv: (t) => `FileKit ${t} är en säker, integritetsfokuserad motor som slår samman och konverterar ljud- och videofiler blixtsnabbt direkt i din webbläsare.`,
    da: (t) => `FileKit ${t} er en privatlivsfokuseret mediemotor, der konverterer, redigerer og behandler lyd- og videofiler lokalt i din browser.`,
    fi: (t) => `FileKit ${t} on yksityisyyttä kunnioittava mediamoottori, joka muuntaa, yhdistää ja pakkaa ääni- ja videotiedostoja suoraan selaimessasi.`,
    no: (t) => `FileKit ${t} er en personvernorientert mediemotor som konverterer, redigerer og behandler lyd- og videofiler lokalt i nettleseren din.`,
    pl: (t) => `FileKit ${t} to silnik przetwarzania multimediów zorientowany na prywatność, który konwertuje, łączy i kompresuje pliki audio i wideo bezpośrednio w przeglądarce.`,
    cs: (t) => `FileKit ${t} je modul pro zpracování médií zaměřený na soukromí, který převádí, spojuje a komprimuje zvukové a video soubory přímo v prohlížeči.`,
    hu: (t) => `A FileKit ${t} egy adatvédelemre összpontosító médiamotor, amely audio- és videofájlokat konvertál, egyesít és tömörít közvetlenül a böngészőben.`,
    ro: (t) => `FileKit ${t} este un motor multimedia axat pe confidențialitate pentru conversia, unirea și compresia fișierelor audio și video direct în browser.`,
    bg: (t) => `FileKit ${t} е медиен двигател, ориентиран към поверителността, който конвертира, обединява и компресира аудио и видео файлове директно в браузъра.`,
    el: (t) => `Το FileKit ${t} είναι ένας κινητήρας επεξεργασίας πολυμέσων με επίκεντρο το απόρρητο για τη μετατροπή, ένωση και συμπίεση αρχείων απευθείας στον browser.`,
    sk: (t) => `FileKit ${t} je mediálny modul zameraný na súkromie, ktorý konvertuje, spája a komprimuje zvukové a video súbory priamo v prehliadači.`,
    sl: (t) => `FileKit ${t} je medijski mehanizem, osredotočen na zasebnost, ki pretvarja, združuje in stiska zvočne in video datoteke neposredno v brskalniku.`,
    ru: (t) => `FileKit ${t} — это медиа-движок, ориентированный на конфиденциальность, который конвертирует, объединяет и сжимает аудио и видео прямо в браузере.`,
    uk: (t) => `FileKit ${t} — це медіа-рушій, орієнтований на конфіденційність, який конвертує, об'єднує та стискає аудіо та відео файли прямо у браузері.`,
    lv: (t) => `FileKit ${t} ir privātumam pielāgots mediju dzinējs, kas konvertē, apvieno un saspiež audio un video failus tieši pārlūkprogrammā.`,
    lt: (t) => `FileKit ${t} yra privatumui pritaikytas medijos variklis, kuris konvertuoja, sujungia ir suspaudžia garso ir vaizdo failus tiesiai naršyklėje.`,
    tr: (t) => `FileKit ${t}, medya dosyalarını dönüştürmek ve sıkıştırmak için donanım ivmesini kullanan gizlilik odaklı bir medya işleme motorudur.`,
    ar: (t) => `تعد ${t} من FileKit محركاً آمناً لمعالجة الوسائط يركز على الخصوصية مع الاستفادة من تسريع العتاد لتحويل وضغط ملفات الوسائط بسرعة فائقة.`,
    he: (t) => `FileKit ${t} הוא מנוע עיבוד מדיה המתמקד בפרטיות, הממיר, עורך ומעבד קובצי אודיו ווידאו מקומית בדפדפן בביצועים גבוהים.`,
    hi: (t) => `FileKit ${t} एक गोपनीयता-प्रथम, इन-ब्राउज़र मीडिया प्रोसेसिंग इंजन है जो ऑडियो और वीडियो फ़ाइलों को उच्च प्रदर्शन के साथ स्थानीय रूप से परिवर्तित और संसाधित करता है।`,
    id: (t) => `FileKit ${t} adalah mesin pemrosesan media berbasis privasi di browser yang mengonversi, mengedit, dan memproses file audio dan video secara lokal dengan performa tinggi.`,
    ms: (t) => `FileKit ${t} ialah enjin pemprosesan media dalam pelayar yang mengutamakan privasi, menukar, menyunting dan memproses fail audio dan video secara setempat dengan prestasi tinggi.`,
    th: (t) => `FileKit ${t} เป็นเอ็นจิ้นการประมวลผลสื่อในเบราว์เซอร์ที่เน้นความเป็นส่วนตัว ซึ่งแปลง แก้ไข และประมวลผลไฟล์เสียงและวิดีโอในเครื่องด้วยประสิทธิภาพสูง`,
    vi: (t) => `FileKit ${t} là công cụ xử lý đa phương tiện ưu tiên quyền riêng tư trong trình duyệt, giúp chuyển đổi, chỉnh sửa và xử lý file âm thanh và video cục bộ với hiệu suất cao.`,
    fil: (t) => `Ang FileKit ${t} ay isang privacy-first na media engine na nagko-convert, nag-e-edit, at nagpoproseso ng audio at video files nang lokal na may mataas na performance.`,
    ja: (t) => `FileKit ${t} は、高いパフォーマンスでオーディオおよびビデオファイルをローカルで変換、編集、処理するプライバシー優先のメディアエンジンです。`,
    ko: (t) => `FileKit ${t}은 오디오 및 비디오 파일을 고성능으로 로컬 변환, 편집 및 처리하는 개인정보 보호 중심의 브라우저 내 미디어 엔진입니다.`,
    "zh-CN": (t) => `FileKit ${t} 是一个注重隐私的浏览器端媒体处理引擎，可在本地高性能转换、编辑和处理音频及视频文件。`,
    "zh-TW": (t) => `FileKit ${t} 是一個注重隱私的瀏覽器端媒體處理引擎，可在本機高效能轉換、編輯和處理音訊及影片檔案。`
  },
  pdf: {
    en: (t) => `FileKit ${t} is a fast, 100% private in-browser document utility engineered for secure client-side processing without file uploads.`,
    es: (t) => `FileKit ${t} es una herramienta rápida y 100% privada en el navegador diseñada para un procesamiento seguro en tu dispositivo sin subir archivos.`,
    "es-419": (t) => `FileKit ${t} es una herramienta rápida y 100% privada en el navegador diseñada para procesamiento seguro en tu dispositivo sin subir archivos.`,
    de: (t) => `FileKit ${t} ist ein schnelles und 100% privates Browser-Tool für die sichere Verarbeitung direkt auf Ihrem Gerät ohne Datei-Uploads.`,
    fr: (t) => `FileKit ${t} est un utilitaire rapide et 100% privé s'exécutant dans votre navigateur pour un traitement sécurisé sur votre appareil sans téléversement.`,
    pt: (t) => `O FileKit ${t} é uma ferramenta rápida e 100% privada no navegador projetada para processamento seguro no seu dispositivo sem envio de ficheiros.`,
    "pt-BR": (t) => `O FileKit ${t} é uma ferramenta rápida e 100% privada no navegador projetada para processamento seguro no seu dispositivo sem envio de arquivos.`,
    it: (t) => `FileKit ${t} è un'utilità veloce e privata al 100% nel browser progettata per l'elaborazione sicura sul tuo dispositivo senza caricare file.`,
    nl: (t) => `FileKit ${t} is een snelle, 100% privé browsergebaseerde documenttool ontworpen voor veilige verwerking op uw apparaat zonder bestands-uploads.`,
    ca: (t) => `FileKit ${t} és una eina ràpida i 100% privada al navegador dissenyada per a un processament segur al vostre dispositiu sense pujar fitxers.`,
    sv: (t) => `FileKit ${t} är ett snabbt och 100% privat webbläsarverktyg utformat för säker behandling direkt på din enhet utan filuppladdningar.`,
    da: (t) => `FileKit ${t} er et hurtigt og 100% privat browserværktøj designet til sikker behandling direkte på din enhed uden filupload.`,
    fi: (t) => `FileKit ${t} on nopea ja 100% yksityinen selaintyökalu, joka on suunniteltu turvalliseen käsittelyyn suoraan laitteellasi ilman tiedostojen latausta.`,
    no: (t) => `FileKit ${t} er et raskt og 100% privat nettleserverktøy utviklet for sikker behandling direkte på enheten din uten filopplasting.`,
    pl: (t) => `FileKit ${t} to szybkie i w 100% prywatne narzędzie działające w przeglądarce, zaprojektowane do bezpiecznego przetwarzania plików bez ich przesyłania.`,
    cs: (t) => `FileKit ${t} je rychlý a 100% soukromý nástroj v prohlížeči navržený pro bezpečné zpracování přímo na vašem zařízení bez nahrávání souborů.`,
    hu: (t) => `A FileKit ${t} egy gyors és 100%-ban privát böngészőeszköz, amelyet a fájlok biztonságos, helyi feldolgozására terveztek feltöltés nélkül.`,
    ro: (t) => `FileKit ${t} este un utilitar rapid și 100% privat în browser conceput pentru procesare sigură direct pe dispozitivul dvs. fără încărcare de fișiere.`,
    bg: (t) => `FileKit ${t} е бърз и 100% поверителен инструмент за браузър, създаден за сигурна обработка на файлове директно на вашето устройство без качване.`,
    el: (t) => `Το FileKit ${t} είναι ένα γρήγορο και 100% ιδιωτικό εργαλείο εγγράφων στον browser, σχεδιασμένο για ασφαλή επεξεργασία στη συσκευή σας χωρίς μεταφόρτωση αρχείων.`,
    sk: (t) => `FileKit ${t} je rýchly a 100% súkromný nástroj v prehliadači navrhnutý na bezpečné spracovanie priamo na vašom zariadení bez nahrávania súborov.`,
    sl: (t) => `FileKit ${t} je hitro in 100% zasebno orodje v brskalniku, zasnovano za varno obdelavo neposredno v vaši napravi brez nalaganja datotek.`,
    ru: (t) => `FileKit ${t} — это быстрый и на 100% конфиденциальный инструмент для безопасной обработки файлов прямо в браузере без загрузки на сервер.`,
    uk: (t) => `FileKit ${t} — це швидкий і на 100% конфіденційний інструмент для безпечної обробки документів прямо у браузері без завантаження на сервер.`,
    lv: (t) => `FileKit ${t} ir ātrs un 100% privāts pārlūkprogrammas rīks, kas paredzēts drošai dokumentu apstrādei tieši jūsu ierīcē bez failu augšupielādes.`,
    lt: (t) => `FileKit ${t} yra greitas ir 100% privatus naršyklės įrankis, skirtas saugiam dokumentų apdorojimui tiesiogiai jūsų įrenginyje be failų įkėlimo.`,
    tr: (t) => `FileKit ${t}, dosya yüklemesi olmadan güvenli istemci tarafı işleme için tasarlanmış hızlı, %100 özel bir tarayıcı içi belge yardımcı programıdır.`,
    ar: (t) => `أداة ${t} هي أداة سريعة وخاصة 100% داخل المتصفح مصممة لمعالجة المستندات بأمان على جهازك دون رفع أي ملفات.`,
    he: (t) => `FileKit ${t} הוא כלי מסמכים מהיר ופרטי ב-100% בדפדפן המיועד לעיבוד מאובטח ישירות במכשיר שלך ללא העלאת קבצים.`,
    hi: (t) => `FileKit ${t} एक तेज़, 100% निजी इन-ब्राउज़र दस्तावेज़ उपयोगिता है जो फ़ाइल अपलोड के बिना आपके डिवाइस पर सुरक्षित प्रोसेसिंग के लिए डिज़ाइन की गई है।`,
    id: (t) => `FileKit ${t} adalah utilitas dokumen dalam browser yang cepat dan 100% pribadi yang dirancang untuk pemrosesan aman di perangkat Anda tanpa mengunggah file.`,
    ms: (t) => `FileKit ${t} ialah utiliti dokumen dalam pelayar yang pantas dan 100% peribadi yang direka untuk pemprosesan selamat pada peranti anda tanpa memuat naik fail.`,
    th: (t) => `FileKit ${t} เป็นยูทิลิตี้เอกสารในเบราว์เซอร์ที่รวดเร็วและเป็นส่วนตัว 100% ออกแบบมาเพื่อการประมวลผลอย่างปลอดภัยบนอุปกรณ์ของคุณโดยไม่ต้องอัปโหลดไฟล์`,
    vi: (t) => `FileKit ${t} là tiện ích tài liệu trong trình duyệt nhanh chóng, riêng tư 100% được thiết kế để xử lý an toàn trên thiết bị của bạn mà không cần tải file lên.`,
    fil: (t) => `Ang FileKit ${t} ay isang mabilis, 100% pribadong in-browser document utility na idinisenyo para sa secure na pagpoproseso nang hindi nag-a-upload ng mga file.`,
    ja: (t) => `FileKit ${t} は、ファイルをサーバーに送信せず、ブラウザ上で100%安全にローカル処理するために設計された高速ツールです。`,
    ko: (t) => `FileKit ${t}은 파일 업로드 없이 브라우저 내에서 안전하게 로컬 처리하도록 설계된 빠르고 100% 비공개 문서 유틸리티입니다.`,
    "zh-CN": (t) => `FileKit ${t} 是一款快速、100% 私密的浏览器端工具，专为在设备上安全处理文件而设计，无需上传至服务器。`,
    "zh-TW": (t) => `FileKit ${t} 是一款快速、100% 私密的瀏覽器端工具，專為在裝置上安全處理檔案而設計，無需上傳至伺服器。`
  }
};

let ts = `import { SupportedLocale } from "../i18n/locales";
import { ToolFamilyKey } from "./categories";

// Comprehensive 39-locale entity definitions for rich semantic SEO, AEO, and GEO
export const ENTITY_TEMPLATES: Record<ToolFamilyKey, Record<SupportedLocale, (toolTitle: string) => string>> = {\n`;

for (const fam of FAMILIES) {
  ts += `  ${fam}: {\n`;
  for (const loc of LOCALES) {
    const fn = ENTITY_TEMPLATES[fam]?.[loc] || ENTITY_TEMPLATES[fam]?.en;
    const sample = fn("__TITLE__");
    // Split on __TITLE__ to construct the function code
    const parts = sample.split("__TITLE__");
    const p1 = parts[0].replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');
    const p2 = (parts[1] || '').replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');
    const key = loc.includes('-') ? `"${loc}"` : loc;
    ts += `    ${key}: (toolTitle: string) => \`${p1}\${toolTitle}${p2}\`,\n`;
  }
  ts += `  },\n`;
}

ts += `};\n\n`;
ts += `export function getEntityDefinition(family: ToolFamilyKey, toolTitle: string, locale: SupportedLocale = "en"): string {\n`;
ts += `  const famDict = ENTITY_TEMPLATES[family] || ENTITY_TEMPLATES.pdf;\n`;
ts += `  const template = famDict[locale] || famDict.en;\n`;
ts += `  return template(toolTitle);\n`;
ts += `}\n`;

writeFileSync(OUT, ts, 'utf-8');
console.log('✅ Generated entityDefinitions.ts across all 39 locales for all 7 families!');
