import os
import re

SLUG_TITLES_39 = {
  "/compress-pdf-to-2mb": {
    "en": "Compress PDF to 2MB Online Free",
    "es": "Comprimir PDF a 2 MB Online Gratis",
    "es-419": "Comprimir PDF a 2 MB Online Gratis",
    "de": "PDF auf 2 MB komprimieren Kostenlos Online",
    "fr": "Compresser PDF à 2 Mo Gratuit en Ligne",
    "pt": "Comprimir PDF para 2 MB Grátis Online",
    "pt-BR": "Comprimir PDF para 2 MB Grátis Online",
    "it": "Comprimi PDF a 2 MB Gratis Online",
    "nl": "PDF naar 2 MB comprimeren Gratis Online",
    "ca": "Comprimir PDF a 2 MB Online Gratuït",
    "sv": "Komprimera PDF till 2 MB Gratis Online",
    "da": "Komprimer PDF til 2 MB Gratis Online",
    "fi": "Pakkaa PDF 2 megatavuun Ilmaiseksi Verkossa",
    "no": "Komprimer PDF til 2 MB Gratis på Nett",
    "pl": "Kompresuj PDF do 2 MB Za Darmo Online",
    "cs": "Komprimovat PDF na 2 MB Zdarma Online",
    "hu": "PDF tömörítése 2 MB-ra Ingyen Online",
    "ro": "Comprimă PDF la 2 MB Gratuit Online",
    "bg": "Компресиране на PDF до 2 MB Безплатно Онлайн",
    "el": "Συμπίεση PDF σε 2 MB Δωρεάν Online",
    "sk": "Komprimovať PDF na 2 MB Zadarmo Online",
    "sl": "Stisni PDF na 2 MB Brezplačno na Spletu",
    "ru": "Сжать PDF до 2 МБ Бесплатно Онлайн",
    "uk": "Стиснути PDF до 2 МБ Безкоштовно Онлайн",
    "lv": "Saspiest PDF līdz 2 MB Bezmaksas Tiešsaistē",
    "lt": "Glaudinti PDF iki 2 MB Nemokamai Internete",
    "tr": "PDF'i 2 MB Boyutuna Sıkıştır Ücretsiz Çevrimiçi",
    "ar": "ضغط PDF إلى 2 ميغابايت مجاناً أونلاين",
    "he": "דחיסת PDF ל-2 MB בחינם אונליין",
    "hi": "PDF को 2 MB तक कंप्रेस करें मुफ़्त ऑनलाइन",
    "id": "Kompres PDF ke 2 MB Gratis Online",
    "ms": "Mampatkan PDF ke 2 MB Percuma Dalam Talian",
    "th": "บีบอัด PDF ให้เหลือ 2 MB ฟรีออนไลน์",
    "vi": "Nén PDF xuống 2 MB Miễn phí Trực tuyến",
    "fil": "I-compress ang PDF sa 2 MB Libre Online",
    "ja": "PDFを2MB以下に圧縮 無料オンライン",
    "ko": "PDF를 2MB로 압축 무료 온라인",
    "zh-CN": "将 PDF 压缩至 2MB 以内 在线免费",
    "zh-TW": "將 PDF 壓縮至 2MB 以內 免費線上"
  },
  "/compress-image-to-100kb": {
    "en": "Compress Image to 100KB Online Free",
    "es": "Comprimir imagen a 100 KB Online Gratis",
    "es-419": "Comprimir imagen a 100 KB Online Gratis",
    "de": "Bild auf 100 KB komprimieren Kostenlos Online",
    "fr": "Compresser l'image à 100 Ko Gratuit en Ligne",
    "pt": "Comprimir imagem para 100 KB Grátis Online",
    "pt-BR": "Comprimir imagem para 100 KB Grátis Online",
    "it": "Comprimi immagine a 100 KB Gratis Online",
    "nl": "Afbeelding naar 100 KB comprimeren Gratis Online",
    "ca": "Comprimir imatge a 100 KB Online Gratuït",
    "sv": "Komprimera bild till 100 KB Gratis Online",
    "da": "Komprimer billede til 100 KB Gratis Online",
    "fi": "Pakkaa kuva 100 kilotavuun Ilmaiseksi Verkossa",
    "no": "Komprimer bilde til 100 KB Gratis på Nett",
    "pl": "Kompresuj obraz do 100 KB Za Darmo Online",
    "cs": "Komprimovat obrázek na 100 KB Zdarma Online",
    "hu": "Kép tömörítése 100 KB-ra Ingyen Online",
    "ro": "Comprimă Imaginea la 100 KB Gratuit Online",
    "bg": "Компресиране на изображение до 100 KB Безплатно Онлайн",
    "el": "Συμπίεση εικόνας σε 100 KB Δωρεάν Online",
    "sk": "Komprimovať obrázok na 100 KB Zadarmo Online",
    "sl": "Stisni sliko na 100 KB Brezplačno na Spletu",
    "ru": "Сжать изображение до 100 КБ Бесплатно Онлайн",
    "uk": "Стиснути зображення до 100 КБ Безкоштовно Онлайн",
    "lv": "Saspiest attēlu līdz 100 KB Bezmaksas Tiešsaistē",
    "lt": "Glaudinti vaizdą iki 100 KB Nemokamai Internete",
    "tr": "Görseli 100 KB Boyutuna Sıkıştır Ücretsiz Çevrimiçi",
    "ar": "ضغط الصورة إلى 100 كيلوبايت مجاناً أونلاين",
    "he": "דחיסת תמונה ל-100 KB בחינם אונליין",
    "hi": "इमेज को 100 KB तक कंप्रेस करें मुफ़्त ऑनलाइन",
    "id": "Kompres Gambar ke 100 KB Gratis Online",
    "ms": "Mampatkan Imej ke 100 KB Percuma Dalam Talian",
    "th": "บีบอัดรูปภาพให้เหลือ 100 KB ฟรีออนไลน์",
    "vi": "Nén ảnh xuống 100 KB Miễn phí Trực tuyến",
    "fil": "I-compress ang Larawan sa 100 KB Libre Online",
    "ja": "画像を100KB以下に圧縮 無料オンライン",
    "ko": "이미지를 100KB로 압축 무료 온라인",
    "zh-CN": "将图片压缩至 100KB 以内 在线免费",
    "zh-TW": "將圖片壓縮至 100KB 以內 免費線上"
  },
  "/compress-image-to-200kb": {
    "en": "Compress Image to 200KB Online Free",
    "es": "Comprimir imagen a 200 KB Online Gratis",
    "es-419": "Comprimir imagen a 200 KB Online Gratis",
    "de": "Bild auf 200 KB komprimieren Kostenlos Online",
    "fr": "Compresser l'image à 200 Ko Gratuit en Ligne",
    "pt": "Comprimir imagem para 200 KB Grátis Online",
    "pt-BR": "Comprimir imagem para 200 KB Grátis Online",
    "it": "Comprimi immagine a 200 KB Gratis Online",
    "nl": "Afbeelding naar 200 KB comprimeren Gratis Online",
    "ca": "Comprimir imatge a 200 KB Online Gratuït",
    "sv": "Komprimera bild till 200 KB Gratis Online",
    "da": "Komprimer billede til 200 KB Gratis Online",
    "fi": "Pakkaa kuva 200 kilotavuun Ilmaiseksi Verkossa",
    "no": "Komprimer bilde til 200 KB Gratis på Nett",
    "pl": "Kompresuj obraz do 200 KB Za Darmo Online",
    "cs": "Komprimovat obrázek na 200 KB Zdarma Online",
    "hu": "Kép tömörítése 200 KB-ra Ingyen Online",
    "ro": "Comprimă Imaginea la 200 KB Gratuit Online",
    "bg": "Компресиране на изображение до 200 KB Безплатно Онлайн",
    "el": "Συμπίεση εικόνας σε 200 KB Δωρεάν Online",
    "sk": "Komprimovať obrázok na 200 KB Zadarmo Online",
    "sl": "Stisni sliko na 200 KB Brezplačno na Spletu",
    "ru": "Сжать изображение до 200 КБ Бесплатно Онлайн",
    "uk": "Стиснути зображення до 200 КБ Безкоштовно Онлайн",
    "lv": "Saspiest attēlu līdz 200 KB Bezmaksas Tiešsaistē",
    "lt": "Glaudinti vaizdą iki 200 KB Nemokamai Internete",
    "tr": "Görseli 200 KB Boyutuna Sıkıştır Ücretsiz Çevrimiçi",
    "ar": "ضغط الصورة إلى 200 كيلوبايت مجاناً أونلاين",
    "he": "דחיסת תמונה ל-200 KB בחינם אונליין",
    "hi": "इमेज को 200 KB तक कंप्रेस करें मुफ़्त ऑनलाइन",
    "id": "Kompres Gambar ke 200 KB Gratis Online",
    "ms": "Mampatkan Imej ke 200 KB Percuma Dalam Talian",
    "th": "บีบอัดรูปภาพให้เหลือ 200 KB ฟรีออนไลน์",
    "vi": "Nén ảnh xuống 200 KB Miễn phí Trực tuyến",
    "fil": "I-compress ang Larawan sa 200 KB Libre Online",
    "ja": "画像を200KB以下に圧縮 無料オンライン",
    "ko": "이미지를 200KB로 압축 무료 온라인",
    "zh-CN": "将图片压缩至 200KB 以内 在线免费",
    "zh-TW": "將圖片壓縮至 200KB 以內 免費線上"
  },
  "/compress-image-to-500kb": {
    "en": "Compress Image to 500KB Online Free",
    "es": "Comprimir imagen a 500 KB Online Gratis",
    "es-419": "Comprimir imagen a 500 KB Online Gratis",
    "de": "Bild auf 500 KB komprimieren Kostenlos Online",
    "fr": "Compresser l'image à 500 Ko Gratuit en Ligne",
    "pt": "Comprimir imagem para 500 KB Grátis Online",
    "pt-BR": "Comprimir imagem para 500 KB Grátis Online",
    "it": "Comprimi immagine a 500 KB Gratis Online",
    "nl": "Afbeelding naar 500 KB comprimeren Gratis Online",
    "ca": "Comprimir imatge a 500 KB Online Gratuït",
    "sv": "Komprimera bild till 500 KB Gratis Online",
    "da": "Komprimer billede til 500 KB Gratis Online",
    "fi": "Pakkaa kuva 500 kilotavuun Ilmaiseksi Verkossa",
    "no": "Komprimer bilde til 500 KB Gratis på Nett",
    "pl": "Kompresuj obraz do 500 KB Za Darmo Online",
    "cs": "Komprimovat obrázek na 500 KB Zdarma Online",
    "hu": "Kép tömörítése 500 KB-ra Ingyen Online",
    "ro": "Comprimă Imaginea la 500 KB Gratuit Online",
    "bg": "Компресиране на изображение до 500 KB Безплатно Онлайн",
    "el": "Συμπίεση εικόνας σε 500 KB Δωρεάν Online",
    "sk": "Komprimovať obrázok na 500 KB Zadarmo Online",
    "sl": "Stisni sliko na 500 KB Brezplačno na Spletu",
    "ru": "Сжать изображение до 500 КБ Бесплатно Онлайн",
    "uk": "Стиснути зображення до 500 КБ Безкоштовно Онлайн",
    "lv": "Saspiest attēlu līdz 500 KB Bezmaksas Tiešsaistē",
    "lt": "Glaudinti vaizdą iki 500 KB Nemokamai Internete",
    "tr": "Görseli 500 KB Boyutuna Sıkıştır Ücretsiz Çevrimiçi",
    "ar": "ضغط الصورة إلى 500 كيلوبايت مجاناً أونلاين",
    "he": "דחיסת תמונה ל-500 KB בחינם אונליין",
    "hi": "इमेज को 500 KB तक कंप्रेस करें मुफ़्त ऑनलाइन",
    "id": "Kompres Gambar ke 500 KB Gratis Online",
    "ms": "Mampatkan Imej ke 500 KB Percuma Dalam Talian",
    "th": "บีบอัดรูปภาพให้เหลือ 500 KB ฟรีออนไลน์",
    "vi": "Nén ảnh xuống 500 KB Miễn phí Trực tuyến",
    "fil": "I-compress ang Larawan sa 500 KB Libre Online",
    "ja": "画像を500KB以下に圧縮 無料オンライン",
    "ko": "이미지를 500KB로 압축 무료 온라인",
    "zh-CN": "将图片压缩至 500KB 以内 在线免费",
    "zh-TW": "將圖片壓縮至 500KB 以內 免費線上"
  },
  "/compress-image-to-1mb": {
    "en": "Compress Image to 1MB Online Free",
    "es": "Comprimir imagen a 1 MB Online Gratis",
    "es-419": "Comprimir imagen a 1 MB Online Gratis",
    "de": "Bild auf 1 MB komprimieren Kostenlos Online",
    "fr": "Compresser l'image à 1 Mo Gratuit en Ligne",
    "pt": "Comprimir imagem para 1 MB Grátis Online",
    "pt-BR": "Comprimir imagem para 1 MB Grátis Online",
    "it": "Comprimi immagine a 1 MB Gratis Online",
    "nl": "Afbeelding naar 1 MB comprimeren Gratis Online",
    "ca": "Comprimir imatge a 1 MB Online Gratuït",
    "sv": "Komprimera bild till 1 MB Gratis Online",
    "da": "Komprimer billede til 1 MB Gratis Online",
    "fi": "Pakkaa kuva 1 megatavuun Ilmaiseksi Verkossa",
    "no": "Komprimer bilde til 1 MB Gratis på Nett",
    "pl": "Kompresuj obraz do 1 MB Za Darmo Online",
    "cs": "Komprimovat obrázek na 1 MB Zdarma Online",
    "hu": "Kép tömörítése 1 MB-ra Ingyen Online",
    "ro": "Comprimă Imaginea la 1 MB Gratuit Online",
    "bg": "Компресиране на изображение до 1 MB Безплатно Онлайн",
    "el": "Συμπίεση εικόνας σε 1 MB Δωρεάν Online",
    "sk": "Komprimovať obrázok na 1 MB Zadarmo Online",
    "sl": "Stisni sliko na 1 MB Brezplačno na Spletu",
    "ru": "Сжать изображение до 1 МБ Бесплатно Онлайн",
    "uk": "Стиснути зображення до 1 МБ Безкоштовно Онлайн",
    "lv": "Saspiest attēlu līdz 1 MB Bezmaksas Tiešsaistē",
    "lt": "Glaudinti vaizdą iki 1 MB Nemokamai Internete",
    "tr": "Görseli 1 MB Boyutuna Sıkıştır Ücretsiz Çevrimiçi",
    "ar": "ضغط الصورة إلى 1 ميغابايت مجاناً أونلاين",
    "he": "דחיסת תמונה ל-1 MB בחינם אונליין",
    "hi": "इमेज को 1 MB तक कंप्रेस करें मुफ़्त ऑनलाइन",
    "id": "Kompres Gambar ke 1 MB Gratis Online",
    "ms": "Mampatkan Imej ke 1 MB Percuma Dalam Talian",
    "th": "บีบอัดรูปภาพให้เหลือ 1 MB ฟรีออนไลน์",
    "vi": "Nén ảnh xuống 1 MB Miễn phí Trực tuyến",
    "fil": "I-compress ang Larawan sa 1 MB Libre Online",
    "ja": "画像を1MB以下に圧縮 無料オンライン",
    "ko": "이미지를 1MB로 압축 무료 온라인",
    "zh-CN": "将图片压缩至 1MB 以内 在线免费",
    "zh-TW": "將圖片壓縮至 1MB 以內 免費線上"
  },
  "/blur-image": {
    "en": "Blur Image Online Free",
    "es": "Desenfocar imagen Online Gratis",
    "es-419": "Desenfocar imagen Online Gratis",
    "de": "Bild weichzeichnen Kostenlos Online",
    "fr": "Flouter l'image Gratuit en Ligne",
    "pt": "Desfocar imagem Grátis Online",
    "pt-BR": "Desfocar imagem Grátis Online",
    "it": "Sfoca immagine Gratis Online",
    "nl": "Afbeelding vervagen Gratis Online",
    "ca": "Desenfocar imatge Online Gratuït",
    "sv": "Gör bilden oskarp Gratis Online",
    "da": "Slør billede Gratis Online",
    "fi": "Sumenna kuva Ilmaiseksi Verkossa",
    "no": "Gjør bildet uskarpt Gratis på Nett",
    "pl": "Rozmyj obraz Za Darmo Online",
    "cs": "Rozostřit obrázek Zdarma Online",
    "hu": "Kép elmosása Ingyen Online",
    "ro": "Estompează Imaginea Gratuit Online",
    "bg": "Замъгляване на изображение Безплатно Онлайн",
    "el": "Θόλωμα εικόνας Δωρεάν Online",
    "sk": "Rozostriť obrázok Zadarmo Online",
    "sl": "Zamegli sliko Brezplačno na Spletu",
    "ru": "Размыть изображение Бесплатно Онлайн",
    "uk": "Розмити зображення Безкоштовно Онлайн",
    "lv": "Aizmiglot attēlu Bezmaksas Tiešsaistē",
    "lt": "Sulieti vaizdą Nemokamai Internete",
    "tr": "Görseli Bulanıklaştır Ücretsiz Çevrimiçi",
    "ar": "تعتيم الصورة مجاناً أونلاين",
    "he": "טשטוש תמונה בחינם אונליין",
    "hi": "इमेज ब्लर करें मुफ़्त ऑनलाइन",
    "id": "Kaburkan Gambar Gratis Online",
    "ms": "Kaburkan Imej Percuma Dalam Talian",
    "th": "เบลอรูปภาพ ฟรีออนไลน์",
    "vi": "Làm mờ ảnh Miễn phí Trực tuyến",
    "fil": "I-blur ang Larawan Libre Online",
    "ja": "画像をぼかす 無料オンライン",
    "ko": "이미지 블러 처리 무료 온라인",
    "zh-CN": "图片模糊处理 在线免费",
    "zh-TW": "圖片模糊處理 免費線上"
  },
  "/grayscale-image": {
    "en": "Grayscale Image Online Free",
    "es": "Convertir imagen a escala de grises Online Gratis",
    "es-419": "Convertir imagen a escala de grises Online Gratis",
    "de": "Bild in Graustufen umwandeln Kostenlos Online",
    "fr": "Convertir l'image en noir et blanc Gratuit en Ligne",
    "pt": "Converter imagem para escala de cinzentos Grátis Online",
    "pt-BR": "Converter imagem para escala de cinza Grátis Online",
    "it": "Converti immagine in scala di grigi Gratis Online",
    "nl": "Afbeelding naar grijswaarden Gratis Online",
    "ca": "Convertir imatge a escala de grisos Online Gratuït",
    "sv": "Gör bilden gråskalig Gratis Online",
    "da": "Lav gråtonebillede Gratis Online",
    "fi": "Muunna kuva harmaasävyiseksi Ilmaiseksi Verkossa",
    "no": "Gjør bilde om til gråtoner Gratis på Nett",
    "pl": "Zmień obraz na czarno-biały Za Darmo Online",
    "cs": "Převést obrázek do stupňů šedi Zdarma Online",
    "hu": "Fekete-fehér kép készítése Ingyen Online",
    "ro": "Transformă Imaginea în Tonuri de Gri Gratuit Online",
    "bg": "Черно-бяло изображение Безплатно Онлайн",
    "el": "Μετατροπή εικόνας σε κλίμακα του γκρι Δωρεάν Online",
    "sk": "Previesť obrázok na čiernobiely Zadarmo Online",
    "sl": "Spremeni sliko v sivine Brezplačno na Spletu",
    "ru": "Черно-белое изображение Бесплатно Онлайн",
    "uk": "Чорно-біле зображення Безкоштовно Онлайн",
    "lv": "Pārvērst attēlu pelēktoņos Bezmaksas Tiešsaistē",
    "lt": "Paversti vaizdą nespalvotu Nemokamai Internete",
    "tr": "Görseli Gri Tona Dönüştür Ücretsiz Çevrimiçi",
    "ar": "تحويل الصورة لتدرج رمادي مجاناً أونلاين",
    "he": "המרת תמונה לגווני אפור בחינם אונליין",
    "hi": "इमेज को ब्लैक एंड व्हाइट बनाएं मुफ़्त ऑनलाइन",
    "id": "Ubah Gambar ke Hitam Putih Gratis Online",
    "ms": "Tukar Imej ke Skala Kelabu Percuma Dalam Talian",
    "th": "แปลงภาพเป็นโทนขาวดำ ฟรีออนไลน์",
    "vi": "Chuyển ảnh sang đen trắng Miễn phí Trực tuyến",
    "fil": "Gawing Grayscale ang Larawan Libre Online",
    "ja": "画像を白黒・グレースケールに変換 無料オンライン",
    "ko": "이미지 흑백 그레이스케일 변환 무료 온라인",
    "zh-CN": "图片转黑白灰度 在线免费",
    "zh-TW": "圖片轉黑白灰階 免費線上"
  },
  "/invert-image": {
    "en": "Invert Image Online Free",
    "es": "Invertir colores de imagen Online Gratis",
    "es-419": "Invertir colores de imagen Online Gratis",
    "de": "Bildfarben invertieren Kostenlos Online",
    "fr": "Inverser les couleurs de l'image Gratuit en Ligne",
    "pt": "Inverter cores da imagem Grátis Online",
    "pt-BR": "Inverter cores da imagem Grátis Online",
    "it": "Inverti colori immagine Gratis Online",
    "nl": "Afbeelding kleuren omkeren Gratis Online",
    "ca": "Invertir colors de la imatge Online Gratuït",
    "sv": "Invertera bildfärger Gratis Online",
    "da": "Inverter billedfarver Gratis Online",
    "fi": "Käännä kuvan värit Ilmaiseksi Verkossa",
    "no": "Inverter bildefarger Gratis på Nett",
    "pl": "Odwróć kolory obrazu Za Darmo Online",
    "cs": "Invertovat barvy obrázku Zdarma Online",
    "hu": "Kép színeinek megfordítása Ingyen Online",
    "ro": "Inversează Culorile Imaginii Gratuit Online",
    "bg": "Инвертиране на цветовете на изображение Безплатно Онлайн",
    "el": "Αντιστροφή χρωμάτων εικόνας Δωρεάν Online",
    "sk": "Invertovať farby obrázka Zadarmo Online",
    "sl": "Invertiraj barve slike Brezplačno na Spletu",
    "ru": "Инвертировать цвета изображения Бесплатно Онлайн",
    "uk": "Інвертувати кольори зображення Безкоштовно Онлайн",
    "lv": "Invertēt attēla krāsas Bezmaksas Tiešsaistē",
    "lt": "Invertuoti vaizdo spalvas Nemokamai Internete",
    "tr": "Görsel Renklerini Tersine Çevir Ücretsiz Çevrimiçi",
    "ar": "عكس ألوان الصورة مجاناً أونلاين",
    "he": "היפוך צבעי תמונה בחינם אונליין",
    "hi": "इमेज के रंग उलटें मुफ़्त ऑनलाइन",
    "id": "Balikkan Warna Gambar Gratis Online",
    "ms": "Songsangkan Warna Imej Percuma Dalam Talian",
    "th": "กลับสีรูปภาพ ฟรีออนไลน์",
    "vi": "Đảo ngược màu ảnh Miễn phí Trực tuyến",
    "fil": "Baligtarin ang Kulay ng Larawan Libre Online",
    "ja": "画像のネガ反転・色反転 無料オンライン",
    "ko": "이미지 색상 반전 무료 온라인",
    "zh-CN": "图片颜色反转 在线免费",
    "zh-TW": "圖片色彩反轉 免費線上"
  },
  "/flip-image": {
    "en": "Flip Image Online Free",
    "es": "Voltear imagen Online Gratis",
    "es-419": "Voltear imagen Online Gratis",
    "de": "Bild spiegeln Kostenlos Online",
    "fr": "Retourner l'image Gratuit en Ligne",
    "pt": "Inverter imagem horizontalmente Grátis Online",
    "pt-BR": "Virar imagem horizontalmente Grátis Online",
    "it": "Capovolgi immagine Gratis Online",
    "nl": "Afbeelding spiegelen Gratis Online",
    "ca": "Voltejar imatge Online Gratuït",
    "sv": "Vänd bild Gratis Online",
    "da": "Spejlvend billede Gratis Online",
    "fi": "Käännä kuva Ilmaiseksi Verkossa",
    "no": "Speilvend bilde Gratis på Nett",
    "pl": "Przerzuć obraz Za Darmo Online",
    "cs": "Překlopit obrázek Zdarma Online",
    "hu": "Kép tükrözése Ingyen Online",
    "ro": "Întoarce Imaginea Gratuit Online",
    "bg": "Обръщане на изображение Безплатно Онлайн",
    "el": "Αναστροφή εικόνας Δωρεάν Online",
    "sk": "Preklopiť obrázok Zadarmo Online",
    "sl": "Zrcali sliko Brezplačno na Spletu",
    "ru": "Отразить изображение Бесплатно Онлайн",
    "uk": "Віддзеркалити зображення Безкоштовно Онлайн",
    "lv": "Apmest attēlu spoguļskatā Bezmaksas Tiešsaistē",
    "lt": "Apversti vaizdą veidrodiškai Nemokamai Internete",
    "tr": "Görseli Çevir Ücretsiz Çevrimiçi",
    "ar": "قلب الصورة مجاناً أونلاين",
    "he": "שיקוף תמונה בחינם אונליין",
    "hi": "इमेज फ्लिप करें मुफ़्त ऑनलाइन",
    "id": "Balik Gambar Secara Horizontal Gratis Online",
    "ms": "Balikkan Imej Secara Mendatar Percuma Dalam Talian",
    "th": "พลิกรูปภาพแนวนอน ฟรีออนไลน์",
    "vi": "Lật hình ảnh ngang Miễn phí Trực tuyến",
    "fil": "I-flip ang Larawan Libre Online",
    "ja": "画像を左右・上下反転 無料オンライン",
    "ko": "이미지 좌우/상하 반전 무료 온라인",
    "zh-CN": "图片水平/垂直翻转 在线免费",
    "zh-TW": "圖片水平/垂直翻轉 免費線上"
  },
  "/convert-audio": {
    "en": "Convert Audio Files Online Free",
    "es": "Convertir archivos de audio Online Gratis",
    "es-419": "Convertir archivos de audio Online Gratis",
    "de": "Audiodateien konvertieren Kostenlos Online",
    "fr": "Convertir des fichiers audio Gratuit en Ligne",
    "pt": "Converter ficheiros de áudio Grátis Online",
    "pt-BR": "Converter arquivos de áudio Grátis Online",
    "it": "Converti file audio Gratis Online",
    "nl": "Audiobestanden converteren Gratis Online",
    "ca": "Convertir fitxers d'àudio Online Gratuït",
    "sv": "Konvertera ljudfiler Gratis Online",
    "da": "Konverter lydfiler Gratis Online",
    "fi": "Muunna äänitiedostoja Ilmaiseksi Verkossa",
    "no": "Konverter lydfiler Gratis på Nett",
    "pl": "Konwertuj pliki audio Za Darmo Online",
    "cs": "Převést audio soubory Zdarma Online",
    "hu": "Hangfájlok konvertálása Ingyen Online",
    "ro": "Convertește Fișiere Audio Gratuit Online",
    "bg": "Конвертиране на аудио файлове Безплатно Онлайн",
    "el": "Μετατροπή αρχείων ήχου Δωρεάν Online",
    "sk": "Konvertovať audio súbory Zadarmo Online",
    "sl": "Pretvori zvočne datoteke Brezplačno na Spletu",
    "ru": "Конвертировать аудиофайлы Бесплатно Онлайн",
    "uk": "Конвертувати аудіофайли Безкоштовно Онлайн",
    "lv": "Konvertēt audio failus Bezmaksas Tiešsaistē",
    "lt": "Konvertuoti garso failus Nemokamai Internete",
    "tr": "Ses Dosyalarını Dönüştür Ücretsiz Çevrimiçi",
    "ar": "تحويل الملفات الصوتية مجاناً أونلاين",
    "he": "המרת קובצי אודיו בחינם אונליין",
    "hi": "ऑडियो फाइलें कन्वर्ट करें मुफ़्त ऑनलाइन",
    "id": "Konversi File Audio Gratis Online",
    "ms": "Tukar Fail Audio Percuma Dalam Talian",
    "th": "แปลงไฟล์เสียง ฟรีออนไลน์",
    "vi": "Chuyển đổi tệp âm thanh Miễn phí Trực tuyến",
    "fil": "I-convert ang mga Audio File Libre Online",
    "ja": "音声ファイルを変換 無料オンライン",
    "ko": "오디오 파일 변환 무료 온라인",
    "zh-CN": "音频格式转换 在线免费",
    "zh-TW": "音訊格式轉換 免費線上"
  },
  "/compress-video": {
    "en": "Compress Video Files Online Free",
    "es": "Comprimir archivos de video Online Gratis",
    "es-419": "Comprimir archivos de video Online Gratis",
    "de": "Videodateien komprimieren Kostenlos Online",
    "fr": "Compresser des fichiers vidéo Gratuit en Ligne",
    "pt": "Comprimir ficheiros de vídeo Grátis Online",
    "pt-BR": "Comprimir arquivos de vídeo Grátis Online",
    "it": "Comprimi file video Gratis Online",
    "nl": "Videobestanden comprimeren Gratis Online",
    "ca": "Comprimir fitxers de vídeo Online Gratuït",
    "sv": "Komprimera videofiler Gratis Online",
    "da": "Komprimer videofiler Gratis Online",
    "fi": "Pakkaa videotiedostoja Ilmaiseksi Verkossa",
    "no": "Komprimer videofiler Gratis på Nett",
    "pl": "Kompresuj pliki wideo Za Darmo Online",
    "cs": "Komprimovat video soubory Zdarma Online",
    "hu": "Videófájlok tömörítése Ingyen Online",
    "ro": "Comprimă Fișiere Video Gratuit Online",
    "bg": "Компресиране на видео файлове Безплатно Онлайн",
    "el": "Συμπίεση αρχείων βίντεο Δωρεάν Online",
    "sk": "Komprimovať video súbory Zadarmo Online",
    "sl": "Stisni video datoteke Brezplačno na Spletu",
    "ru": "Сжать видеофайлы Бесплатно Онлайн",
    "uk": "Стиснути відеофайли Безкоштовно Онлайн",
    "lv": "Saspiest video failus Bezmaksas Tiešsaistē",
    "lt": "Glaudinti vaizdo failus Nemokamai Internete",
    "tr": "Video Dosyalarını Sıkıştır Ücretsiz Çevrimiçi",
    "ar": "ضغط ملفات الفيديو مجاناً أونلاين",
    "he": "דחיסת קובצי וידאו בחינם אונליין",
    "hi": "वीडियो फाइलें कंप्रेस करें मुफ़्त ऑनलाइन",
    "id": "Kompres File Video Gratis Online",
    "ms": "Mampatkan Fail Video Percuma Dalam Talian",
    "th": "บีบอัดไฟล์วิดีโอ ฟรีออนไลน์",
    "vi": "Nén tệp video Miễn phí Trực tuyến",
    "fil": "I-compress ang mga Video File Libre Online",
    "ja": "動画ファイルを圧縮 無料オンライン",
    "ko": "동영상 파일 압축 무료 온라인",
    "zh-CN": "视频文件压缩 在线免费",
    "zh-TW": "影片檔案壓縮 免費線上"
  },
  "/compress-audio": {
    "en": "Compress Audio Files Online Free",
    "es": "Comprimir archivos de audio Online Gratis",
    "es-419": "Comprimir archivos de audio Online Gratis",
    "de": "Audiodateien komprimieren Kostenlos Online",
    "fr": "Compresser des fichiers audio Gratuit en Ligne",
    "pt": "Comprimir ficheiros de áudio Grátis Online",
    "pt-BR": "Comprimir arquivos de áudio Grátis Online",
    "it": "Comprimi file audio Gratis Online",
    "nl": "Audiobestanden comprimeren Gratis Online",
    "ca": "Comprimir fitxers d'àudio Online Gratuït",
    "sv": "Komprimera ljudfiler Gratis Online",
    "da": "Komprimer lydfiler Gratis Online",
    "fi": "Pakkaa äänitiedostoja Ilmaiseksi Verkossa",
    "no": "Komprimer lydfiler Gratis på Nett",
    "pl": "Kompresuj pliki audio Za Darmo Online",
    "cs": "Komprimovat audio soubory Zdarma Online",
    "hu": "Hangfájlok tömörítése Ingyen Online",
    "ro": "Comprimă Fișiere Audio Gratuit Online",
    "bg": "Компресиране на аудио файлове Безплатно Онлайн",
    "el": "Συμπίεση αρχείων ήχου Δωρεάν Online",
    "sk": "Komprimovať audio súbory Zadarmo Online",
    "sl": "Stisni zvočne datoteke Brezplačno na Spletu",
    "ru": "Сжать аудиофайлы Бесплатно Онлайн",
    "uk": "Стиснути аудіофайли Безкоштовно Онлайн",
    "lv": "Saspiest audio failus Bezmaksas Tiešsaistē",
    "lt": "Glaudinti garso failus Nemokamai Internete",
    "tr": "Ses Dosyalarını Sıkıştır Ücretsiz Çevrimiçi",
    "ar": "ضغط ملفات الصوت مجاناً أونلاين",
    "he": "דחיסת קובצי אודיו בחינם אונליין",
    "hi": "ऑडियो फाइलें कंप्रेस करें मुफ़्त ऑनलाइन",
    "id": "Kompres File Audio Gratis Online",
    "ms": "Mampatkan Fail Audio Percuma Dalam Talian",
    "th": "บีบอัดไฟล์เสียง ฟรีออนไลน์",
    "vi": "Nén tệp âm thanh Miễn phí Trực tuyến",
    "fil": "I-compress ang mga Audio File Libre Online",
    "ja": "音声ファイルを圧縮 無料オンライン",
    "ko": "오디오 파일 압축 무료 온라인",
    "zh-CN": "音频文件压缩 在线免费",
    "zh-TW": "音訊檔案壓縮 免費線上"
  }
}

def json_repr(d, indent=2):
    import json
    return json.dumps(d, ensure_ascii=False, indent=indent)

with open('src/utils/i18nHelper.ts', 'r', encoding='utf-8') as f:
    helper_code = f.read()

# Replace between `const EXACT_SLUG_TITLES: Record<string, Record<string, string>> = {` and `};`
pattern = r'const EXACT_SLUG_TITLES: Record<string, Record<string, string>> = \{[\s\S]*?\n  \};'
match = re.search(pattern, helper_code)
if match:
    helper_code = helper_code.replace(match.group(0), "const EXACT_SLUG_TITLES: Record<string, Record<string, string>> = " + json_repr(SLUG_TITLES_39) + ";")
    with open('src/utils/i18nHelper.ts', 'w', encoding='utf-8') as f:
        f.write(helper_code)
    print("Successfully replaced EXACT_SLUG_TITLES with all 39 languages!")
else:
    print("Could not find pattern for EXACT_SLUG_TITLES")
