import os
import re
import json

print("=== POPULATING 39 LANGUAGES IN PdfCompressionWorkspace.tsx ===")

PDF_WORKSPACE_LANGS = {
  "bg": {
    "dropPdf": "Плъзнете PDF документа тук или изберете",
    "supportsPdf": "Поддържа стандартни PDF документи до 50 MB",
    "privacyPdf": "🔒 Вашият PDF се обработва локално в браузъра и не се качва.",
    "originalSize": "Оригинален размер",
    "chooseAnother": "Изберете друг",
    "compressing": "Компресиране на PDF локално...",
    "noBeneficial": "Няма полезно намаляване",
    "targetNotMet": "PDF е намален, но желаният размер не можа да бъде достигнат безопасно",
    "alreadyBelow": "Вашият PDF вече е под желания размер",
    "compressedOk": "PDF е компресиран успешно",
    "noReductionDesc": "Този PDF вече е ефективно компресиран. Оригиналният файл е запазен.",
    "original": "Оригинал",
    "newSize": "Нов размер",
    "pages": "Страници",
    "reduction": "Намаляване",
    "processingLocal": "Обработка: Локален браузър",
    "downloadOriginal": "Изтегляне на оригинален PDF",
    "downloadBest": "Изтегляне на най-добър резултат",
    "downloadCompressed": "Изтегляне на компресиран PDF",
    "adjustSettings": "Настройки",
    "settingsTitle": "Настройки за компресиране на PDF",
    "compressionGoal": "Цел на компресирането",
    "betterQuality": "По-добро качество",
    "betterQualityDesc": "Запазва повече визуални детайли",
    "balanced": "Балансирано",
    "balancedDesc": "Препоръчва се за повечето документи",
    "smallerFile": "По-малък файл",
    "smallerFileDesc": "Приоритет на максимално намаляване на размера",
    "targetFileSize": "Целеви размер на файла",
    "quickTargets": "Бързи цели:",
    "targetOutcome": "Целев резултат",
    "below2mb": "Под 2 MB",
    "targetOutcomeDesc": "Този инструмент автоматично оптимизира вашия PDF под 2 MB за лесно споделяне.",
    "compressBtn": "Компресиране на PDF",
    "recompressBtn": "Повторно компресиране",
    "compressingBtn": "Компресиране на PDF..."
  },
  "el": {
    "dropPdf": "Σύρετε το έγγραφο PDF εδώ ή περιηγηθείτε",
    "supportsPdf": "Υποστηρίζει έγγραφα PDF έως 50 MB",
    "privacyPdf": "🔒 Το PDF επεξεργάζεται τοπικά στο πρόγραμμα περιήγησης και δεν ανεβαίνει.",
    "originalSize": "Αρχικό μέγεθος",
    "chooseAnother": "Επιλογή άλλου",
    "compressing": "Συμπίεση PDF τοπικά...",
    "noBeneficial": "Χωρίς σημαντική μείωση",
    "targetNotMet": "Το PDF μειώθηκε αλλά δεν επετεύχθη το επιθυμητό μέγεθος",
    "alreadyBelow": "Το PDF σας είναι ήδη μικρότερο από το επιθυμητό μέγεθος",
    "compressedOk": "Το PDF συμπιέστηκε επιτυχώς",
    "noReductionDesc": "Αυτό το PDF είναι ήδη βελτιστοποιημένο. Το αρχικό αρχείο διατηρήθηκε.",
    "original": "Αρχικό",
    "newSize": "Νέο μέγεθος",
    "pages": "Σελίδες",
    "reduction": "Μείωση",
    "processingLocal": "Επεξεργασία: Τοπικός περιηγητής",
    "downloadOriginal": "Λήψη αρχικού PDF",
    "downloadBest": "Λήψη καλύτερου αποτελέσματος",
    "downloadCompressed": "Λήψη συμπιεσμένου PDF",
    "adjustSettings": "Προσαρμογή ρυθμίσεων",
    "settingsTitle": "Ρυθμίσεις συμπίεσης PDF",
    "compressionGoal": "Στόχος συμπίεσης",
    "betterQuality": "Καλύτερη ποιότητα",
    "betterQualityDesc": "Διατηρεί περισσότερες οπτικές λεπτομέρειες",
    "balanced": "Ισορροπημένο",
    "balancedDesc": "Συνιστάται για τα περισσότερα έγγραφα",
    "smallerFile": "Μικρότερο αρχείο",
    "smallerFileDesc": "Προτεραιότητα στη μέγιστη μείωση μεγέθους",
    "targetFileSize": "Μέγεθος αρχείου στόχου",
    "quickTargets": "Γρήγοροι στόχοι:",
    "targetOutcome": "Επιθυμητό αποτέλεσμα",
    "below2mb": "Κάτω από 2 MB",
    "targetOutcomeDesc": "Βελτιστοποιεί αυτόματα το PDF σας κάτω από 2 MB.",
    "compressBtn": "Συμπίεση PDF",
    "recompressBtn": "Επανασυμπίεση PDF",
    "compressingBtn": "Συμπίεση PDF..."
  },
  "ru": {
    "dropPdf": "Перетащите документ PDF сюда или выберите файл",
    "supportsPdf": "Поддерживает стандартные документы PDF до 50 МБ",
    "privacyPdf": "🔒 Ваш PDF обрабатывается локально в браузере и не загружается на сервер.",
    "originalSize": "Исходный размер",
    "chooseAnother": "Выбрать другой",
    "compressing": "Локальное сжатие PDF...",
    "noBeneficial": "Уменьшение не требуется",
    "targetNotMet": "PDF уменьшен, но целевой размер не достигнут безопасно",
    "alreadyBelow": "Ваш PDF уже меньше целевого размера",
    "compressedOk": "PDF успешно сжат",
    "noReductionDesc": "Этот PDF уже оптимально сжат. Исходный файл сохранен.",
    "original": "Оригинал",
    "newSize": "Новый размер",
    "pages": "Страницы",
    "reduction": "Уменьшение",
    "processingLocal": "Обработка: Локальный браузер",
    "downloadOriginal": "Скачать исходный PDF",
    "downloadBest": "Скачать лучший результат",
    "downloadCompressed": "Скачать сжатый PDF",
    "adjustSettings": "Настройки",
    "settingsTitle": "Настройки сжатия PDF",
    "compressionGoal": "Цель сжатия",
    "betterQuality": "Высокое качество",
    "betterQualityDesc": "Сохраняет больше визуальных деталей",
    "balanced": "Сбалансированное",
    "balancedDesc": "Рекомендуется для большинства документов",
    "smallerFile": "Меньший размер",
    "smallerFileDesc": "Максимальное уменьшение размера файла",
    "targetFileSize": "Целевой размер файла",
    "quickTargets": "Быстрый выбор:",
    "targetOutcome": "Целевой результат",
    "below2mb": "Менее 2 МБ",
    "targetOutcomeDesc": "Этот инструмент автоматически сжимает PDF до размера менее 2 МБ.",
    "compressBtn": "Сжать PDF",
    "recompressBtn": "Сжать повторно",
    "compressingBtn": "Сжатие PDF..."
  },
  "uk": {
    "dropPdf": "Перетягніть документ PDF сюди або виберіть файл",
    "supportsPdf": "Підтримує стандартні документи PDF до 50 МБ",
    "privacyPdf": "🔒 Ваш PDF обробляється локально у браузері та не завантажується на сервер.",
    "originalSize": "Початковий розмір",
    "chooseAnother": "Вибрати інший",
    "compressing": "Локальне стиснення PDF...",
    "noBeneficial": "Зменшення не потрібне",
    "targetNotMet": "PDF зменшено, але цільовий розмір не досягнуто безпечно",
    "alreadyBelow": "Ваш PDF вже менший за цільовий розмір",
    "compressedOk": "PDF успішно стиснуто",
    "noReductionDesc": "Цей PDF вже оптимально стиснутий. Початковий файл збережено.",
    "original": "Оригінал",
    "newSize": "Новий розмір",
    "pages": "Сторінки",
    "reduction": "Зменшення",
    "processingLocal": "Обробка: Локальний браузер",
    "downloadOriginal": "Завантажити оригінальний PDF",
    "downloadBest": "Завантажити найкращий результат",
    "downloadCompressed": "Завантажити стиснутий PDF",
    "adjustSettings": "Налаштування",
    "settingsTitle": "Налаштування стиснення PDF",
    "compressionGoal": "Ціль стиснення",
    "betterQuality": "Краща якість",
    "betterQualityDesc": "Зберігає більше візуальних деталей",
    "balanced": "Збалансоване",
    "balancedDesc": "Рекомендовано для більшості документів",
    "smallerFile": "Менший файл",
    "smallerFileDesc": "Максимальне зменшення розміру файлу",
    "targetFileSize": "Цільовий розмір файлу",
    "quickTargets": "Швидкий вибір:",
    "targetOutcome": "Цільовий результат",
    "below2mb": "Менше 2 МБ",
    "targetOutcomeDesc": "Цей інструмент автоматично стискає PDF до розміру менше 2 МБ.",
    "compressBtn": "Стиснути PDF",
    "recompressBtn": "Стиснути повторно",
    "compressingBtn": "Стиснення PDF..."
  },
  "zh": {
    "dropPdf": "将 PDF 文件拖放到此处或点击选择",
    "supportsPdf": "支持高达 50 MB 的标准 PDF 文档",
    "privacyPdf": "🔒 您的 PDF 在浏览器本地处理，绝不会上传至服务器。",
    "originalSize": "原始大小",
    "chooseAnother": "选择其他文件",
    "compressing": "正在本地极速压缩 PDF...",
    "noBeneficial": "无需进一步压缩",
    "targetNotMet": "PDF 已压缩，但未能安全达到目标大小",
    "alreadyBelow": "您的 PDF 大小已低于目标大小",
    "compressedOk": "PDF 压缩成功",
    "noReductionDesc": "使用当前设置，该 PDF 已具备最高压缩率。已为您保留原文件。",
    "original": "原大小",
    "newSize": "新大小",
    "pages": "页数",
    "reduction": "压缩率",
    "processingLocal": "处理方式：浏览器本地处理",
    "downloadOriginal": "下载原始 PDF",
    "downloadBest": "下载最佳结果",
    "downloadCompressed": "下载压缩后的 PDF",
    "adjustSettings": "调整压缩设置",
    "settingsTitle": "PDF 压缩选项",
    "compressionGoal": "压缩目标",
    "betterQuality": "较高画质",
    "betterQualityDesc": "保留更多图像细节与清晰度",
    "balanced": "均衡模式",
    "balancedDesc": "推荐大多数文档使用",
    "smallerFile": "最小体积",
    "smallerFileDesc": "优先极致缩减文件体积",
    "targetFileSize": "目标文件大小",
    "quickTargets": "常用预设：",
    "targetOutcome": "压缩目标",
    "below2mb": "2 MB 以内",
    "targetOutcomeDesc": "该工具自动将 PDF 优化至 2 MB 以内，方便邮件发送与在线上传。",
    "compressBtn": "立即压缩 PDF",
    "recompressBtn": "重新压缩 PDF",
    "compressingBtn": "正在压缩 PDF..."
  },
  "ja": {
    "dropPdf": "PDFファイルをここにドロップまたは選択",
    "supportsPdf": "50 MBまでの標準PDFドキュメントをサポート",
    "privacyPdf": "🔒 PDFはブラウザ上で安全にローカル処理され、サーバーにアップロードされません。",
    "originalSize": "元のサイズ",
    "chooseAnother": "別のファイルを選択",
    "compressing": "PDFをローカルで圧縮中...",
    "noBeneficial": "これ以上の圧縮は不要です",
    "targetNotMet": "PDFは圧縮されましたが、指定されたサイズには届きませんでした",
    "alreadyBelow": "指定サイズよりすでに小さいファイルです",
    "compressedOk": "PDFの圧縮が完了しました",
    "noReductionDesc": "このPDFは選択された設定ですでに効率的に圧縮されています。元のファイルが保持されます。",
    "original": "元のサイズ",
    "newSize": "圧縮後サイズ",
    "pages": "ページ数",
    "reduction": "削減率",
    "processingLocal": "処理：ローカルブラウザ",
    "downloadOriginal": "元のPDFをダウンロード",
    "downloadBest": "最適な結果をダウンロード",
    "downloadCompressed": "圧縮されたPDFをダウンロード",
    "adjustSettings": "設定を調整",
    "settingsTitle": "PDF圧縮設定",
    "compressionGoal": "圧縮目標",
    "betterQuality": "高画質優先",
    "betterQualityDesc": "視覚的な詳細と鮮明さを維持",
    "balanced": "バランス（推奨）",
    "balancedDesc": "一般的な文書に最適",
    "smallerFile": "ファイルサイズ優先",
    "smallerFileDesc": "ファイルサイズの削減を最優先",
    "targetFileSize": "目標ファイルサイズ",
    "quickTargets": "プリセット:",
    "targetOutcome": "目標結果",
    "below2mb": "2 MB以下",
    "targetOutcomeDesc": "メール送信やアップロード用にPDFを自動的に2 MB以下に最適化します。",
    "compressBtn": "PDFを圧縮",
    "recompressBtn": "PDFを再圧縮",
    "compressingBtn": "PDFを圧縮中..."
  },
  "ko": {
    "dropPdf": "PDF 문서를 여기에 끌어다 놓거나 파일 선택",
    "supportsPdf": "최대 50 MB의 표준 PDF 문서 지원",
    "privacyPdf": "🔒 PDF는 브라우저에서 로컬로 안전하게 처리되며 서버에 업로드되지 않습니다.",
    "originalSize": "원본 크기",
    "chooseAnother": "다른 파일 선택",
    "compressing": "PDF 로컬 압축 중...",
    "noBeneficial": "추가 압축 불필요",
    "targetNotMet": "PDF가 압축되었으나 목표 크기에 안전하게 도달하지 못했습니다",
    "alreadyBelow": "PDF가 이미 목표 크기보다 작습니다",
    "compressedOk": "PDF 압축 완료",
    "noReductionDesc": "선택한 설정에서 이미 최적화된 파일입니다. 원본 파일이 유지됩니다.",
    "original": "원본",
    "newSize": "압축 크기",
    "pages": "페이지",
    "reduction": "압축률",
    "processingLocal": "처리: 로컬 브라우저",
    "downloadOriginal": "원본 PDF 다운로드",
    "downloadBest": "최적 결과 다운로드",
    "downloadCompressed": "압축된 PDF 다운로드",
    "adjustSettings": "설정 조정",
    "settingsTitle": "PDF 압축 설정",
    "compressionGoal": "압축 목표",
    "betterQuality": "고품질",
    "betterQualityDesc": "선명도 및 세부 정보 유지",
    "balanced": "균형 (권장)",
    "balancedDesc": "대부분의 문서에 권장",
    "smallerFile": "작은 파일",
    "smallerFileDesc": "파일 크기 대폭 축소 우선",
    "targetFileSize": "목표 파일 크기",
    "quickTargets": "빠른 선택:",
    "targetOutcome": "목표 결과",
    "below2mb": "2 MB 이하",
    "targetOutcomeDesc": "이메일 첨부 및 업로드를 위해 PDF를 2 MB 이하로 자동 최적화합니다.",
    "compressBtn": "PDF 압축",
    "recompressBtn": "PDF 재압축",
    "compressingBtn": "PDF 압축 중..."
  }
}

with open('src/components/pdf-tools/PdfCompressionWorkspace.tsx', 'r', encoding='utf-8') as f:
    pdf_comp_code = f.read()

# Add to workspaceI18n
for loc, trans_dict in PDF_WORKSPACE_LANGS.items():
    if f'{loc}: {{' not in pdf_comp_code and f'"{loc}": {{' not in pdf_comp_code:
        # insert before the end of workspaceI18n (before `};` around line 819)
        dict_text = f"  {loc}: " + json.dumps(trans_dict, ensure_ascii=False, indent=4).replace("\n", "\n  ") + ",\n"
        idx = pdf_comp_code.find("};\n\nexport default function PdfCompressionWorkspace")
        if idx != -1:
            pdf_comp_code = pdf_comp_code[:idx] + dict_text + pdf_comp_code[idx:]

with open('src/components/pdf-tools/PdfCompressionWorkspace.tsx', 'w', encoding='utf-8') as f:
    f.write(pdf_comp_code)

print("[OK] Successfully injected languages into PdfCompressionWorkspace.tsx!")
