import fs from 'fs';

const locales = [
  "en", "es", "es-419", "de", "fr", "pt", "pt-BR", "it", "nl", "ca",
  "sv", "da", "fi", "no", "pl", "cs", "hu", "ro", "bg", "el",
  "sk", "sl", "ru", "uk", "lv", "lt", "tr", "ar", "he", "hi",
  "id", "ms", "th", "vi", "fil", "ja", "ko", "zh-CN", "zh-TW"
];

// Dictionary of subtitle workspace translations across all 39 locales
const SUBTITLE_I18N = {
  selectFile: {
    "en": (ext) => `Select ${ext} subtitle file`,
    "es": (ext) => `Seleccionar archivo de subtítulos (${ext})`,
    "es-419": (ext) => `Seleccionar archivo de subtítulos (${ext})`,
    "de": (ext) => `Untertiteldatei auswählen (${ext})`,
    "fr": (ext) => `Sélectionner un fichier de sous-titres (${ext})`,
    "pt": (ext) => `Selecionar ficheiro de legendas (${ext})`,
    "pt-BR": (ext) => `Selecionar arquivo de legendas (${ext})`,
    "it": (ext) => `Seleziona file di sottotitoli (${ext})`,
    "nl": (ext) => `Selecteer ondertitelbestand (${ext})`,
    "ca": (ext) => `Selecciona el fitxer de subtítols (${ext})`,
    "sv": (ext) => `Välj undertextfil (${ext})`,
    "da": (ext) => `Vælg undertekstfil (${ext})`,
    "fi": (ext) => `Valitse tekstitystiedosto (${ext})`,
    "no": (ext) => `Velg undertekstfil (${ext})`,
    "pl": (ext) => `Wybierz plik napisów (${ext})`,
    "cs": (ext) => `Vyberte soubor titulků (${ext})`,
    "hu": (ext) => `Válasszon feliratfájlt (${ext})`,
    "ro": (ext) => `Selectează fișierul de subtitrări (${ext})`,
    "bg": (ext) => `Изберете файл със субтитри (${ext})`,
    "el": (ext) => `Επιλέξτε αρχείο υποτίτλων (${ext})`,
    "sk": (ext) => `Vyberte súbor titulkov (${ext})`,
    "sl": (ext) => `Izberite datoteko podnapisov (${ext})`,
    "ru": (ext) => `Выберите файл субтитров (${ext})`,
    "uk": (ext) => `Виберіть файл субтитрів (${ext})`,
    "lv": (ext) => `Izvēlieties subtitru failu (${ext})`,
    "lt": (ext) => `Pasirinkite subtitrų failą (${ext})`,
    "tr": (ext) => `Altyazı Dosyası Seçin (${ext})`,
    "ar": (ext) => `اختر ملف الترجمة (${ext})`,
    "he": (ext) => `בחר קובץ כתוביות (${ext})`,
    "hi": (ext) => `सबটাইटल फ़ाइल चुनें (${ext})`,
    "id": (ext) => `Pilih file subtitle (${ext})`,
    "ms": (ext) => `Pilih fail sari kata (${ext})`,
    "th": (ext) => `เลือกไฟล์คำบรรยาย (${ext})`,
    "vi": (ext) => `Chọn tệp phụ đề (${ext})`,
    "fil": (ext) => `Pumili ng subtitle file (${ext})`,
    "ja": (ext) => `字幕ファイルを選択 (${ext})`,
    "ko": (ext) => `자막 파일 선택 (${ext})`,
    "zh-CN": (ext) => `选择字幕文件 (${ext})`,
    "zh-TW": (ext) => `選擇字幕檔案 (${ext})`
  },
  privacySub: {
    "en": "100% In-Browser · Private & Instant Conversion",
    "es": "100% en el navegador · Conversión instantánea y privada",
    "es-419": "100% en el navegador · Conversión instantánea y privada",
    "de": "100% im Browser · Private & sofortige Konvertierung",
    "fr": "100% dans le navigateur · Conversion privée et instantanée",
    "pt": "100% no navegador · Conversão privada e instantânea",
    "pt-BR": "100% no navegador · Conversão privada e instantânea",
    "it": "100% nel browser · Conversione privata e istantanea",
    "nl": "100% in browser · Snelle & privé conversie",
    "ca": "100% al navegador · Conversió instantània i privada",
    "sv": "100% i webbläsaren · Snabb och privat konvertering",
    "da": "100% i browseren · Privat og øjeblikkelig konvertering",
    "fi": "100% selaimessa · Yksityinen ja välitön muunnos",
    "no": "100% i nettleseren · Privat og øyeblikkelig konvertering",
    "pl": "100% w przeglądarce · Prywatna i natychmiastowa konwersja",
    "cs": "100% v prohlížeči · Soukromý a okamžitý převod",
    "hu": "100%-ban a böngészőben · Privát és azonnali konverzió",
    "ro": "100% în browser · Conversie privată și instantanee",
    "bg": "100% в браузъра · Поверително и мигновено конвертиране",
    "el": "100% στο πρόγραμμα περιήγησης · Ιδιωτική & άμεση μετατροπή",
    "sk": "100% v prehliadači · Súkromná a okamžitá konverzia",
    "sl": "100 % v brskalniku · Zasebna in takojšnja pretvorba",
    "ru": "100% в браузере · Конфиденциальная и мгновенная конвертация",
    "uk": "100% у браузері · Конфіденційна та миттєва конвертація",
    "lv": "100% pārlūkā · Privāta un tūlītēja konvertēšana",
    "lt": "100% naršyklėje · Privatus ir momentinis konvertavimas",
    "tr": "Tarayıcıda %100 · Gizli ve Anında Dönüştürme",
    "ar": "100% في المتصفح · تحويل فوري وخاص",
    "he": "100% בדפדפן · המרה פרטית ומיידית",
    "hi": "100% ब्राउज़र में · निजी और तत्काल कन्वर्जन",
    "id": "100% di browser · Konversi privat & instan",
    "ms": "100% dalam penyemak imbas · Penukaran peribadi & pantas",
    "th": "100% ในเบราว์เซอร์ · การแปลงแบบส่วนตัวและทันที",
    "vi": "100% trong trình duyệt · Chuyển đổi riêng tư & tức thì",
    "fil": "100% sa Browser · Pribado at Mabilisang Pag-convert",
    "ja": "100%ブラウザ内で完結 · 高速＆安全な変換",
    "ko": "100% 브라우저 내 처리 · 즉시 안전한 개인정보 보호 변환",
    "zh-CN": "100% 浏览器本地处理 · 隐私保护即时转换",
    "zh-TW": "100% 瀏覽器本地處理 · 隱私保護即時轉換"
  },
  error: {
    "en": "Failed to parse and convert subtitle file.",
    "es": "Error al procesar y convertir el archivo de subtítulos.",
    "es-419": "Error al procesar y convertir el archivo de subtítulos.",
    "de": "Fehler beim Verarbeiten und Konvertieren der Untertiteldatei.",
    "fr": "Échec de l'analyse et de la conversion du fichier de sous-titres.",
    "pt": "Falha ao processar e converter o ficheiro de legendas.",
    "pt-BR": "Falha ao processar e converter o arquivo de legendas.",
    "it": "Impossibile analizzare e convertire il file dei sottotitoli.",
    "nl": "Kan het ondertitelbestand niet verwerken en converteren.",
    "ca": "Error en analitzar i convertir el fitxer de subtítols.",
    "sv": "Kunde inte analysera och konvertera undertextfilen.",
    "da": "Kunne ikke analysere og konvertere undertekstfilen.",
    "fi": "Tekstitystiedoston jäsentäminen ja muuntaminen epäonnistui.",
    "no": "Kunne ikke analysere og konvertere undertekstfilen.",
    "pl": "Nie udało się przetworzyć i przekonwertować pliku napisów.",
    "cs": "Nepodařilo se zpracovat a převést soubor titulků.",
    "hu": "Nem sikerült feldolgozni és konvertálni a feliratfájlt.",
    "ro": "Nu s-a putut analiza și converti fișierul de subtitrări.",
    "bg": "Неуспешен анализ и конвертиране на файла със субтитри.",
    "el": "Αποτυχία ανάλυσης και μετατροπής αρχείου υποτίτλων.",
    "sk": "Nepodarilo sa spracovať a previesť súbor titulkov.",
    "sl": "Datoteke s podnapisi ni bilo mogoče razčleniti in pretvoriti.",
    "ru": "Не удалось обработать и конвертировать файл субтитров.",
    "uk": "Не вдалося обробити та конвертувати файл субтитрів.",
    "lv": "Neizdevās apstrādāt un konvertēt subtitru failu.",
    "lt": "Nepavyko apdoroti ir konvertuoti subtitrų failo.",
    "tr": "Altyazı dosyası ayrıştırılamadı ve dönüştürülemedi.",
    "ar": "فشل تحليل وتحويل ملف الترجمة.",
    "he": "נכשל בניתוח והמרת קובץ הכתוביות.",
    "hi": "सबटाइटल फ़ाइल को पार्स और कन्वर्ट करने में विफल।",
    "id": "Gagal mengurai dan mengonversi file subtitle.",
    "ms": "Gagal menghuraikan dan menukar fail sari kata.",
    "th": "ไม่สามารถแยกวิเคราะห์และแปลงไฟล์คำบรรยายได้",
    "vi": "Không thể phân tích cú pháp và chuyển đổi tệp phụ đề.",
    "fil": "Nabigong i-parse at i-convert ang subtitle file.",
    "ja": "字幕ファイルの解析および変換に失敗しました。",
    "ko": "자막 파일을 분석하고 변환하지 못했습니다.",
    "zh-CN": "字幕文件解析与转换失败。",
    "zh-TW": "字幕檔案解析與轉換失敗。"
  },
  preview: {
    "en": "Conversion Preview:",
    "es": "Vista previa de la conversión:",
    "es-419": "Vista previa de la conversión:",
    "de": "Vorschau der Konvertierung:",
    "fr": "Aperçu de la conversion :",
    "pt": "Pré-visualização da conversão:",
    "pt-BR": "Pré-visualização da conversão:",
    "it": "Anteprima della conversione:",
    "nl": "Conversievoorbeeld:",
    "ca": "Vista prèvia de la conversió:",
    "sv": "Förhandsgranskning av konvertering:",
    "da": "Forhåndsvisning af konvertering:",
    "fi": "Muunnoksen esikatselu:",
    "no": "Forhåndsvisning av konvertering:",
    "pl": "Podgląd konwersji:",
    "cs": "Náhled převodu:",
    "hu": "Konverzió előnézete:",
    "ro": "Previzualizarea conversiei:",
    "bg": "Преглед на конвертирането:",
    "el": "Προεπισκόπηση μετατροπής:",
    "sk": "Náhľad konverzie:",
    "sl": "Predogled pretvorbe:",
    "ru": "Предварительный просмотр:",
    "uk": "Попередній перегляд:",
    "lv": "Konvertēšanas priekšskatījums:",
    "lt": "Konvertavimo peržiūra:",
    "tr": "Dönüştürme Önizlemesi:",
    "ar": "معاينة التحويل:",
    "he": "תצוגה מקדימה של ההמרה:",
    "hi": "कन्वर्जन पूर्वावलोकन:",
    "id": "Pratinjau Konversi:",
    "ms": "Pratonton Penukaran:",
    "th": "ตัวอย่างการแปลง:",
    "vi": "Xem trước bản chuyển đổi:",
    "fil": "Preview ng Pag-convert:",
    "ja": "変換プレビュー:",
    "ko": "변환 미리보기:",
    "zh-CN": "转换预览：",
    "zh-TW": "轉換預覽："
  },
  download: {
    "en": (name) => `Download ${name}`,
    "es": (name) => `Descargar ${name}`,
    "es-419": (name) => `Descargar ${name}`,
    "de": (name) => `${name} herunterladen`,
    "fr": (name) => `Télécharger ${name}`,
    "pt": (name) => `Descarregar ${name}`,
    "pt-BR": (name) => `Baixar ${name}`,
    "it": (name) => `Scarica ${name}`,
    "nl": (name) => `${name} downloaden`,
    "ca": (name) => `Descarregar ${name}`,
    "sv": (name) => `Ladda ner ${name}`,
    "da": (name) => `Download ${name}`,
    "fi": (name) => `Lataa ${name}`,
    "no": (name) => `Last ned ${name}`,
    "pl": (name) => `Pobierz ${name}`,
    "cs": (name) => `Stáhnout ${name}`,
    "hu": (name) => `${name} letöltése`,
    "ro": (name) => `Descarcă ${name}`,
    "bg": (name) => `Изтегляне на ${name}`,
    "el": (name) => `Λήψη ${name}`,
    "sk": (name) => `Stiahnuť ${name}`,
    "sl": (name) => `Prenesi ${name}`,
    "ru": (name) => `Скачать ${name}`,
    "uk": (name) => `Завантажити ${name}`,
    "lv": (name) => `Lejupielādēt ${name}`,
    "lt": (name) => `Atsisiųsti ${name}`,
    "tr": (name) => `${name} İndir`,
    "ar": (name) => `تنزيل ${name}`,
    "he": (name) => `הורד ${name}`,
    "hi": (name) => `${name} डाउनलोड करें`,
    "id": (name) => `Unduh ${name}`,
    "ms": (name) => `Muat turun ${name}`,
    "th": (name) => `ดาวน์โหลด ${name}`,
    "vi": (name) => `Tải xuống ${name}`,
    "fil": (name) => `I-download ang ${name}`,
    "ja": (name) => `${name} をダウンロード`,
    "ko": (name) => `${name} 다운로드`,
    "zh-CN": (name) => `下载 ${name}`,
    "zh-TW": (name) => `下載 ${name}`
  }
};

console.log('Tested subtitle dictionary definition.');
